XenAdmin/TabPages/GeneralTabPage.cs, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Host.cs
The 'Updates' section on host's General tab displays which packs have been installed onto a host, including the version number
=> CP-10825: Supp Pack installation through XenCenter: Display installed supplemental packs on host's General tab

XenModel/DockerContainer.cs, XenModel/DockerContainers.cs
- when we update the containers, we should update existing objects (if they exist), instead of always creating new ones.
=> CA-159907: Fix refresh issues on containers

XenModel/XenAPI-Extensions/VM.cs
-  A VM can have vGPU if it is HVM and the the allow-vgpu restriction is absent or is non-zero
- allow-vgpu is 0 for HVM Linux VMs
=> CP-11039: Change VM.CanHaveVGpu to use the new allow-vgpu flag

XenAdmin/Help/HelpManager.resx, XenAdmin/MainWindow.Designer.cs, XenAdmin/MainWindow.cs, XenAdmin/MainWindow.ja.resx, XenAdmin/MainWindow.resx, XenAdmin/MainWindow.zh-CN.resx, XenAdmin/TabPages/DockerDetailsPage.Designer.cs, XenAdmin/TabPages/DockerDetailsPage.cs, XenAdmin/TabPages/DockerDetailsPage.ja.resx, XenAdmin/TabPages/DockerDetailsPage.resx, XenAdmin/TabPages/DockerDetailsPage.zh-CN.resx, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.ja.resx, XenModel/Messages.resx, XenModel/Messages.zh-CN.resx
- Showing all detailed information from a docker_inspect call
- The information refresh/polls every 20s while it's open. Also shows time when the last refresh happens.
- Button “Refresh” add, so user can refresh the result. Also shows time when the last refresh happens.
- Add TabPageDetails as value 9903 in HelpManager.resx
=> CP-11053: Add per-container "Details"-Tab

XenAdmin/ConsoleView/VNCTabView.cs
Remove “Remote access is not enabled on this guest” in cream in below condition:
1.RDP status is on
2.PV driver is cream or greater
=> A-160189: Change RDP button display on Console tab

XenAdmin/TabPages/GeneralTabPage.Designer.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/TabPages/GeneralTabPage.resx, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Host.cs, XenModel/XenAPI-Extensions/VDI.cs, XenModel/XenAPI-Extensions/VM.cs
- Show a “Read Caching” section on the General Tab of a VM when the VM is running on a Cream or greater host
- When the Read Caching is enabled, the “Read Caching” section will contain two entries: Status and Disks (list of disks with RC enabled)
- When the Read Caching is disabled, the “Read Caching” section will contain two entries: Status and Reason
(Also fixed the sorting of Messages.resx)
=> CP-10772: Display the read caching status

XenModel/DockerContainers.cs, XenModel/Network/Cache.cs, XenModel/Network/ICache.cs
-ServerXenObject-PropertyChanged eventhandler now returns immediately for a non-VM sender
-Changed IXenObject to VM wherever possible to explicitly state that those methods are expecting VMs
-The UpdateDockerContainersForVM method sets the dockerContainersChanged flag only if there are changes
=> CA-160996: XenCenter: Subscribe to fewer events in DockerContainers

mk/declarations.sh
-Set microversion to 2, because 1 has already been used (hotfix)
=> CA-158601: Bump XenCenter version number for Cream

XenAdmin/MainWindow.cs, XenAdmin/MainWindow.resx, XenAdmin/TabPages/DockerDetailsPage.Designer.cs, XenAdmin/TabPages/DockerDetailsPage.cs, XenAdmin/TabPages/DockerDetailsPage.resx, XenAdmin/TabPages/DockerProcessPage.Designer.cs, XenAdmin/TabPages/DockerProcessPage.cs, XenAdmin/TabPages/DockerProcessPage.resx, XenAdmin/TabPages/GeneralTabPage.cs, XenModel/Actions/DockerContainer/ExecuteContainerPluginAction.cs, XenModel/XenModel.csproj
- Instead of calling the plugin on the UI thread, we call it through an action that we execute asynchronously  and on completion update the UI.
- Pause the refresh timer on leaving the page and resume it when entering the page again.
- We do this for both Processes and Details page.
Also fixing a Null reference exception on General tab.
=> CA-161097: Pause the automatic refresh on Container processes page when the page is not visible

XenAdmin/MainWindow.cs, XenAdmin/TabPages/DockerDetailsPage.cs, XenAdmin/TabPages/DockerProcessPage.cs
This fixes the build errors:
- error CS0108: Warning as Error: 'XenAdmin.TabPages.DockerDetailsPage.Container' hides inherited member 'System.ComponentModel.Component.Container'.
- error CS0108: Warning as Error: 'XenAdmin.TabPages.DockerProcessPage.Container' hides inherited member 'System.ComponentModel.Component.Container'.
=> CA-161097: Renamed Container member to Docker container to fix build failures

XenAdmin/Wizards/NewVMWizard/Page_CloudConfigParameters.cs
=> CP-10926: Make the textbox on Cloud-Config Parameters page read-only (instead of disabled) if the config drive parameters cannot be changed

XenAdmin/Wizards/NewVMWizard/Page_CloudConfigParameters.Designer.cs, XenAdmin/Wizards/NewVMWizard/Page_CloudConfigParameters.cs, XenAdmin/Wizards/NewVMWizard/Page_CloudConfigParameters.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- If failed to retrieve the config parameters, then make the ConfigDriveTemplate textbox read-only and display the reason why it is not editable (similar with what we do for running VMs).
- In the New VM Wizard, if the action on "Reset to Default" button fails, then popup a message box with an error saying that we were unable to retrieve the default parameters. In this case, the ConfigDriveTemplate textbox remains unchanged.
=> CP-10926: Handle exception when running the action that gets the config drive parameters

XenModel/Actions/VM/GpuAssignAction.cs
- The problem was that we didn't create a vgpu if the vgpu_type was null. But for Linux HVM, this is gpu passthrough case.
=> CA-162966: Fix the bug where the GPU value could not be updated via VM Properties for Linux HVM

XenAdmin/TabPages/DockerDetailsPage.Designer.cs, XenAdmin/TabPages/DockerDetailsPage.cs, XenAdmin/TabPages/DockerDetailsPage.resx, XenAdmin/TabPages/DockerProcessPage.resx, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/TabPages/GeneralTabPage.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Implemented changes as follows (copied from ticket):
"
Combine "Docker Version" and "Docker Information" on the VM-General-tab into "Container Management - Docker Status" with the following fields only:
API version
Version
Git Commit
Driver
Index Server Address
Execution Driver
IPv4 Forwarding
In the "Processes" tab, change the name from "Docker Processes" to "Container Processes"
In the "Details" tab, change the name from "Docker Detail" to "Container Details"
In the "Details" tab, drop the top level element "docker_inspect" (XML requires a single root-node, afaik the Windows form treenode does not), or alternatively open the root node by default and rename it to "Inspect Result"
In the "Details" tab, add the "Details"-headline in black on white - just like on the "Processes"-tab
Also, …
=> CA-162989: Container Management GUI usability/homogeneity fixes

XenModel/Actions/StorageLink/SrCreateAction.cs
=> CP-11364: XC to use xapi.secret when creating CIFS SRs

XenAdmin/Diagnostics/Problems/HostProblem/HostOutOfSpaceProblem.cs
- override the Equals function on HostOutOfSpaceProblem to check the disk space requirements, not the Description.
=> CA-164176: Make sure that the Install Update does not get stuck on precheck stage after cleanup on slave

XenModel/Actions/Pool_Patch/GetDiskSpaceRequirementsAction.cs
-Added missing parameter to get_required_space plugin call.
-The required space is not shown in the notification when we are unable to tell how much space is required .
=> CA-163777: [CAR-1711] Incorrect message for cleanup

XenModel/Actions/Pool_Patch/GetDiskSpaceRequirementsAction.cs
-Added missing parameter to get_required_space plugin call.
-The required space is not shown in the notification when we are unable to tell how much space is required .
=> CA-163777: [CAR-1711] Incorrect message for cleanup (for creedence-sp)

XenAdmin/Diagnostics/Problems/HostProblem/HostOutOfSpaceProblem.cs
- override the Equals function on HostOutOfSpaceProblem to check the disk space requirements, not the Description.
=> CA-164176: Make sure that the Install Update does not get stuck on precheck stage after cleanup on slave (for creedence-sp branch)

XenModel/Actions/Pool_Patch/CleanupDiskSpaceAction.cs
-When calling cleanup_disk_space, excluded patch is passed only when it is
not null
=> CA-163778: [CAR-1711] Cleanup not working

XenAdmin/ConsoleView/XSVNCScreen.cs
If user want to switch to RDP, but the RDP IP is empty, original logic will try to connect VNC again, within the VNC re-connection, the Desktop Size lost.
In this situation, we should not switch RDP.
=> CA-164678: Got incorrect guest screen resolution with user's first switch to Remote Desktop from XenCenter Console

XenAdmin/Commands/CrossPoolMigrateCommand.cs, XenAdmin/Commands/CrossPoolMoveVMCommand.cs, XenAdmin/Commands/MoveVMCommand.cs, XenAdmin/Dialogs/VMDialogs/MoveVMDialog.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateWizard.cs, XenAdmin/Wizards/GenericPages/VMMappingSummary.cs, XenAdmin/XenAdmin.csproj, XenAdminTests/WizardTests/CrossPoolMigrateWizardTest.cs, XenModel/Actions/VM/VMMoveAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/Network/NetworkingHelper.cs, XenModel/XenAPI-Extensions/VM.cs
- With these changes, a stopped or suspended VM can be moved across pools; this is performed as a vm migrate operation.
- The intra pool move will continue to be a vdi.copy + destroy operation for stopped VMs, but for suspended VMs we need to do it a as vm migrate operation.
- We use the Cross Pool migrate wizard for both intra and cross pool move operations, but introduced a wizard mode parameter in order to adapt the wizard to the specific operation we want to perform (migrate, move or copy)
=> CP-11032: Remove storage motion constraints: Allow cross-pool move of stopped and suspended VMs

XenAdmin/SettingsPanels/GpuEditPage.cs
-We used to check host.RestrictVgpu instead of checking the API version when populating the dropdown on the GPU Settings page. This is not sufficient anymore as it depends on the license too, so changed the code to check version (vGPU was introduced in Clearwater SP1).
=> CA-164819: On board VGA appears on GPU list

XenAdmin/SettingsPanels/GpuEditPage.cs
-We used to check host.RestrictVgpu instead of checking the API version when populating the dropdown on the GPU Settings page. This is not sufficient anymore as it depends on the license too, so changed the code to check version (vGPU was introduced in Clearwater SP1).
=> CA-164819: On board VGA appears on GPU list (sp)

XenAdmin/ConsoleView/VNCTabView.cs
This code change is to set “switchOnTabOpened” in below condition:
1.	XenCenter have “Automatically switch to the Remote Desktop console when it becomes available" selected
2.	VM have RDP enabled.
3.	XenServer Version is Cream or greater.
=> CA-165464: Switch to RDP on VM with RDP enable if auto-switch selected

XenAdmin/ConsoleView/XSVNCScreen.cs
To solve this long latency issue, we will only scan IPs whose PIF link status is connected.
=> CA-165096: solve XenCenter slow to find RDP interface

XenAdmin/SettingsPanels/GpuEditPage.cs
- When deciding whether to allow GPU configuration on a VM, check if the HA is enabled, not just the the VM's restart priority setting
=> CA-164816: After disabling HA on a pool, it should be possible to apply vGPU/GPU Passthrough to previously protected VMs

XenAdmin/Wizards/PatchingWizard/PlanActions/PlanActionWithSession.cs, XenAdmin/Wizards/RollingUpgradeWizard/PlanActions/AutomaticBackgroundThread.cs, XenAdmin/Wizards/RollingUpgradeWizard/PlanActions/UpgradeManualHostPlanAction.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs, XenModel/Utils/Helpers.cs
- while upgrading a host, throw a HOST_OFFLINE ("Server could not be contacted") exception if the host can no longer be resolved (instead of HANDLE_INVALID)
- also corrected the parameters of the HANDLE_INVALID exception, as an extra parameter is needed for the friendly error name.
- in the UpdateManualHostPlanAction class I replaced Host with the private property _host in several places, so we are no longer trying to resolve the host each time we want to write something into logs
- added some null checks, to avoid reporting null reference exception
=> CA-156200: HANDLE_INVALID shown on Rolling Pool Upgrade completed page

XenAdmin/ConsoleView/VNCGraphicsClient.cs
=> CA-167309: When clipboard sharing is turned off in the options, should not be possible to copy-and-paste from the guest to the XenCenter machine

XenAdmin/ConsoleView/VNCTabView.cs
Check current XenServer Version, if current version is greater than Cream and PV tool installed, do not disable control button.
=> CA-169170: “Switch to Remote desktop” button should not be disabled in Cream when Windows VM installed with latest PV tools.

mk/xenadmin-build.sh
fixing syntax error in xenadmin-build.sh
=> CP-11956: ssh console: Include putty in our installer

XenAdmin/Network/XenConnectionUI.cs
- On receiving a HOST_IS_SLAVE exception, only change connection.Hostname property if we need to connect to the pool master. Leave it unchanged if we are already connected to the pool, as no further action is required. This will ensure that we don't change the Hostname of a slave back to the master, if the user tries to connect to it immediately after it has been removed from the pool.
=> CA-164686: Host got removed from XC when it is removed from a pool

XenAdmin/Dialogs/RepairSRDialog.cs
Passing suppressHistory=false in the MultipleAction's constructor (so no action item will be displayed in the Event view for the MultipleAction itself)
=> CA-120187: Manifestation of "anonymous" action when repairing multiple storages

XenAdmin/Commands/CrossPoolMoveVMCommand.cs, XenAdmin/Commands/MoveVMCommand.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Changed the name of the operation in XenCenter to "Migrate VM" for suspended VMs, instead of "Move VM".
This clarifies the distinction between copy/move and migration:
- running and suspended VMs can only be migrated
- stopped VMs can be moved and copied
=> CP-12282: Semantics of Move / Migrate / Copy for suspended VMs

XenServerHealthCheck/ServerListHelper.cs, XenServerHealthCheck/XenServerHealthCheck.cs, XenServerHealthCheck/XenServerHealthCheckService.cs, XenServerHealthCheck/app.config
Log will be located at ${PROGRAMDATA}/Citrix/XenServerHealthCheck/logs/XenServerHealthCheck.log
=> CP-12158: Add debug log for XenServer Health Check Service

XenModel/Actions/CallHome/CallHomeAuthenticationAction.cs
- added getter and setter to the token property to prevent "Field never assigned" warning
=> CP-12153: Call Home Authentication

XenAdmin/ConsoleView/VNCTabView.cs, XenAdmin/ConsoleView/XSVNCScreen.cs
Auto switch to RDP should be taken after VNC connection got the correct screen resolution.
Also not enable “enable RDP button” before VNC connection get the correct screen resolution.
=> CA-169167: Screen resolution is less than the default value after switch to remote desktop

mk/archive-push.sh, mk/xenadmin-build.sh
Write out the XenCenter version and build number into a version file so
that other tools can determine them from the build artifacts.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> CP-7644: Write XenCenter product version and build number

XenAdmin/ConsoleView/VNCTabView.Designer.cs, XenAdmin/ConsoleView/VNCTabView.resx
button
Removed tooltip from the "Open SSH Console" button
=> CA-172441: Wrong message shown when hover mouse on 'Open SSH Console'

XenModel/XenAPI/PIF.cs, XenModel/XenAPI/Proxy.cs
- update XenModel with the api bindings containing xapi fields and methods related to fcoe
=> CP-12777: Update the api bindings for FCoE

XenAdmin/MainWindow.cs
- Call TransferCallHomeSettingsAction with suppressHistory=true so the action doesn't show on the Events page
- This change also fixes LogsTabTests test failure.
=> CP-12769: Send server connection details to the Health Check Service

WixInstaller/XenCenter.l10n.diff, WixInstaller/XenCenter.wxs
Adding XenServerHealthCheck service to the WiX installer
=> CP-12161: Add the Call Home service to the XenCenter installer

XenAdmin/Controls/CustomDataGraph/DataSet.cs
The unit of VBD IO throughput is changed to MiB after merged all
VBD related data sources from xcp-rrdd to rrdp-iostat,
Signed-off-by: Kaifeng Zhu <kaifeng.zhu@citrix.com>
=> CA-173358: Change the unit of vbd-io-throughput data sources to MiB

XenAdmin/Wizards/ExportWizard/ExportApplianceWizard.cs
The subnet mask is incorrectly set as the static IP.
Update it to correct address.
=> CA-176636: Transfer VM with manually assigned IP doesn't work.

XenModel/Actions/SR/SrAction.cs, XenModel/Actions/SR/SrRepairAction.cs
-When detaching an SR, we detach the slaves first
-When reattaching the SR (SR.plug), we attach the master first
This fix was required by thin provisioning, but it does worth to use the same logic regardless of the provisioning method.
=> CA-173497: Thin provisioning: Repair of SR of thin-provisioning on SR hang without return

XenAdminTests/UnitTests/AlertTests/XenServerPatchAlertTests.cs, XenAdminTests/UnitTests/AlertTests/XenServerUpdateAlertTests.cs
- setup mock connections for the unit tests with a non-null Cache property
- this will fix the test failure due to Alert.IsDismissed() causing NullReferenceException
=> Fix XenServerPatchAlert and XenServerUpdateAlert tests

XenModel/Actions/CallHome/XenServerHealthCheckUpload.cs, XenServerHealthCheck/XenServerHealthCheckBundleUpload.cs
1. Add logs to track the uploading process.
2. Catch the potential exception.
=> CA-178338: XenServerHealthCheckService: bundle uploading update.

mk/xenadmin-build.sh, mk/xenadmintests.sh
- Configured msbuild to build .Net4.5 with visual studio 2013 (13.0)
- Changed .Net platform version to 4.5 in tests script
=> CP-13389: Change build scripts to use .NET 4.5

XenModel/XenServerProxy/RbacCollectorProxy.cs
This changeset fixes the mock to return "True" for host_call_plugin-->trim calls
=> CA-173695: Reclaim freed space is failing with "Index and length must refer to a location with in the string" for AD users

mk/patches/wix_src_patch
fixing wix_src_patch for 3.9 files
=> CP-13390: Update XenCenter installer to require .NET 4.5

XenAdmin/Dialogs/VmSnapshotDialog.cs, XenModel/XenAPI-Extensions/Host.cs
- Add code to check license before offering quiescing on the VM Snapshot dialog
- If the feature is not available, the message displayed is: "This feature is disabled due to license restrictions on the server."
=> CP-13165: Make quiescing into a licensed feature

XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.resx, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.resx, XenAdmin/Wizards/BugToolWizardFiles/BugToolPageDestination.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- no “the” is needed in front of “Citrix Insight Services”  (e.g. “…authenticate with Citrix Insight Services…” and not “…authenticate with the Citrix Insight Services…”)
=> Text corrections in the Health Check dialogs

XenAdmin/Commands/ConvertToThinSRCommand.cs, XenAdminTests/TabsAndMenus/MainMenuGeorge.cs, XenAdminTests/TabsAndMenus/TabsAndMenus.cs
Fixing the unit tests pointed me at the command's CanExecuteCore where the check for Dundee or higher was missing. Fixed that as well.
=> CP-13100: Fixed unit tests and fixed a bug in code

XenAdmin/Core/HealthCheck.cs, XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.cs, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.cs, XenAdmin/Wizards/BugToolWizardFiles/BugToolPageDestination.cs, XenModel/Actions/HealthCheck/GetHealthCheckAnalysisResultAction.cs, XenModel/Actions/HealthCheck/HealthCheckAuthenticationAction.cs, XenModel/Actions/HealthCheck/SaveHealthCheckSettingsAction.cs, XenModel/HealthCheckSettings.cs
Changed all the health check actions to perform the necessary role checks
- HealthCheckAuthenticationAction: changed so it does not save the tokens, so no role checks required in this action (all the checks are performed in SaveHealthCheckSettingsAction)
- GetHealthCheckAnalysisActions: added role checks
On the Health Check Overview dialog, a pool is displayed as read-only if connected as a user with roles that don't permit changing the health check settings:
- the following actions are not available: enroll, edit settings, disable health check, request upload, get analysis result
=> CP-13077: Changes to the Health Check feature to work properly with RBAC

XenModel/HealthCheckSettings.cs
=> CA-182884: Fixed typo which caused the wrong severity icon to be displayed on the Health Check dialog

XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.cs, XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.resx, XenAdmin/SettingsPanels/Wlb/WlbThresholdsPage.Designer.cs, XenAdmin/SettingsPanels/Wlb/WlbThresholdsPage.cs
Revert commit 32c945e104d755b0c172760846ffe57de6d3ad25 which was used to
"Hide Disk Read/Write configuration until the backend server side is ready."
=> CA-134554: Re-enable WLB Disk Read/Write configuration since WLB VPX is ready

XenAdmin/Controls/XenSearch/QueryElement.cs, XenModel/XenSearch/Common.cs
I found I wanted this when debugging, but it could be more generally useful. Note that we now expose the UUID in the General panel, which we didn't when we wrote the search mechanism.
=> CA-185020: Search by UUID

XenModel/Actions/CancellingAction.cs, XenModel/Network/XenConnection.cs, XenModel/XenAPI-Extensions/Task.cs
CA-180128: Ignoring more exceptions on the connection thread when disruption is expected
=> CA-180128: ExpectDisruption flag not working correctly

XenAdmin/Commands/ConvertToThinSRCommand.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdminTests/TabsAndMenus/TabsAndMenus.cs, XenModel/XenAPI-Extensions/SR.cs
- display the Provisioning entries in the General Tab only for iSCSI and LVM SRs
- also changed the checks in the ConvertToThinSRCommand to use SR.IsThinProvisioned property instead of SR.Provisioning
=> CA-184563: Do not show Provisioning method for SRs other than iSCSI and LVM

XenAdmin/Wizards/RollingUpgradeWizard/PlanActions/AutomaticBackgroundThread.cs
In the RPU wizard, after we notice that the host has been rebooted we try to resolve the host from cache, but sometimes the cache is not populated at that point.
Then, because we cannot resolve the host, we cannot check the host version and we assume is a newer version (which might not be true).
This commit adds a call to retry to resolve the host (with timeout).
=> CA-184560: Fix the issue when the RPU wizard cannot check the host version after reboot

XenModel/Actions/Pool/PoolAction.cs, XenModel/PoolJoinRules.cs
Feature leveling should "just work" for Dundee and higher hosts, without the need for us to level them explicitly
=> CP-14085: Feature leveling not needed on pool-join

XenAdmin/Wizards/NewSRWizard.cs
Fixed regression that was caused by hiding the Storage Provisioning page
=> CA-187150: Dundee XenCenter cannot create iSCSI SRs on older hosts

XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard_SelectInstallMethod.cs, XenModel/Actions/HealthCheck/XenServerHealthCheckUpload.cs, XenModel/Utils/Helpers.cs
UrlEncoded all the strings that are used when creating URLs. (Such as untrusted user input: string fileName)
=> CA-187909: Special characters should be URLencoded on HTTP calls

XenAdmin/TabPages/GeneralTabLicenseStatusStringifier.cs, XenAdmin/TabPages/GeneralTabPage.Designer.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenModel/XenAPI-Extensions/Host.cs
Fixed the exception that was caused by a missing null reference check and also the fact that the license status had to be watched only for pools and hosts, so added a check before starting watching the license status of the IXenObject (on GeneralTabPage)
=> CA-188554: XenCenter Error Uncaught exception System.NullReferenceException

XenAdmin/MainWindow.cs
Fixed: "User tasks (e.g. VM import) are reported as errors in XenCenter, when they are cancelled tasks."
=> CA-187932: Cancelled tasks are reported as errors in XenCenter

XenAdmin/SettingsPanels/PerfmonAlertEditPage.cs, XenModel/Actions/Perfmon/PerfmonDefinitionAction.cs, XenModel/Alerts/PerfmonDefinition.cs
Dom0 memory alerts have to be configured in the other_config of the Control Domain (Dom0) and not of the the host. This changeset implements this exception.
=> CA-189084: Control domain memory alerts not getting generated in Xencenter.

XenServerHealthCheck/XenServerHealthCheckBundleUpload.cs, XenServerHealthCheck/XenServerHealthCheckService.cs
Fixing XenServerHealthCheck to use the modern overload of session.login_with_password. With this change XC and all its components are now sending an originator field (with some version added to it).
=> CA-148491: XenServer breaks if any XenAPI client leaks sessions

XenModel/Actions/VM/CreateVMAction.cs, XenModel/XenAPI-Extensions/Host.cs, XenModel/XenAPI-Extensions/VM.cs, XenModel/XenAPI/DeprecatedAttribute.cs, XenModel/XenAPI/Proxy.cs, XenModel/XenAPI/VM.cs, XenModel/XenModel.csproj
This changeset implements the followings:
On creation of a new VM,
* XenCenter will use licensed state of the host to determine whether it should obey/apply the template-recommendation regarding the vendor device.
* If the host is licensed, and the selected template's recommendations suggest that has_vendor_device can be set/should be set to true, as part of VM creation, XenCenter will set the vm's has_vendor_device based on the recommendation using set_has_vendor_device API call (after it has cloned the template and before calling vm.provision).
* XenCenter will not expose details whether 1G or 2G VM is going to be created.
=> CP-14822: UI: New VM Creation: update code to apply recommendations

XenAdmin/Dialogs/Wlb/WlbConfigurationDialog.cs, XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.Designer.cs, XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.cs, XenAdmin/SettingsPanels/Wlb/WlbMetricWeightingPage.resx, XenAdmin/SettingsPanels/Wlb/WlbThresholdsPage.cs
1. Check the Xenserver platform version and display the host disk read/write
threshold and metric weighting for Dundee or later XenServer.
2. Update the metric weighting page to make it autosize-able.
=> CA-194940: WLB - Hide host disk IO settings for XenServer previous to Dundee.

XenModel/XenAPI-Extensions/VM.cs, XenModel/XenAPI-Extensions/VM_guest_metrics.cs
VM.IsWindows  will try to use guest_metrics referenced by the last_booted_record when the guest_metrics on the VM is not available.
This gives some extra chance to detect a Non-Windows VM.
=> CA-187681: Improvement for VM.IsWindows property

XenAdmin/Core/ActionBaseExtensions.cs, XenAdmin/Diagnostics/Problems/VmApplianceProblem/RunningVmApplianceProblem.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Updated the GetLocation extension method for ActionBase objects to return action.Connection.FriendlyName should it have no Host or Pool set up. This way we see location for MeddlingActions.
Also changed some messages (Task Names) to include "VM" in them too, because xe command line initiated VM lifecycle actions looked really misleading after the above fix in XenCenter (Eg. restarting a VM would show up as "Restarting", "server" which would suggest that not just the VM, but the host is being restarted.)
=> CA-159790: [XSO-208] MeddlingActions don't show location information

XenAdmin/Controls/CheckableDataGridView/CheckableDataGridViewController.cs, XenAdmin/Dialogs/LicenseManager/LicenseCheckableDataGridView/LicenseCheckableDataGridViewController.cs, XenAdmin/Dialogs/LicenseManager/LicenseDataGridViewRow.cs
- changed the licenseStatus_ItemUpdated event handler to invoke on the main thread, as this is the only case when a background thread needs to update the storedRows list..All the other reads and writes are taken place on the main (UI) thread
- removed the storedRowsLock as it is not needed since we do all the updates to storedRows on one thread.
=> CP-14472: Remove the lock in the License Manager and ensure that all the updates are done on the main thread.

XenModel/XenAPI-Extensions/Pool.cs
Cherry-picked from cream-indigo:
CA-190393: Update the function that calculates pool license
- use Host.GetEdition function, as this function interprets xapi license string "basic" as Free license in XenCenter
=> CP-15407: Update the function that calculates pool license

mk/patches/wix_src_patch, mk/xenadmin-build.sh
This changeset makes it possible to use InstallDir again - it hasn't worked since we changed to 3.9 from 3.5.
=> CP-15922: Investigate and fix WiX installer for InstallDir Extension UI

XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs
The "Start on Server" VM context menu incorrectly enabled hosts that a VM can
only be started on after a storage migration.  This was due to the fact that
the VMOperationToolStripMenuItem class is used for both "Start on Server" as
well as "Migrate to Server".
This change ensures that start checks are done when a start is requested, and
migration checks otherwise.
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>
=> CA-196231: Don't confuse start-on with migration

WixInstaller/XenCenter.wxs
Revert change of make HKCU->HKMU as error:
"Component 'ProgramFilesShortcut' has both per-user data and a keypath that can be either per-user or per-machine."
In both application menu and desktop shortcut.
This reverts commit e8856343de7de1e9927346713858595d93410b77.
=> Revert "CP-15162: Change the use of HKCU -> HKMU"

XenAdmin/Dialogs/VIFDialog.cs
Fixed bug: "Depending on your workflow you can add a VIF to a VM with a duplicate MAC address without warning."
=> CA-153143: [SCTX-1925] Workflow bug in adding a VIF

WixInstaller/XenCenter.l10n.diff
This fix is to have CN version wizard back in XenCenter installer
Without Language, the l10n installer can only show EN wizard in CN environment.
=> CA-198895: Have parameter Languages back in xencenter.l10n.diff

mk/declarations.sh, mk/package-and-sign.sh, mk/re-branding.sh
After this code change, we also need to modify branding.sh for non-citrix build to use:
REBRANDING_WEB_LATEST_BUILD
instead of 
WEB_LATEST_BUILD
=> CA-198962: Fix compile error of rebranding

XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/PoolJoinRules.cs
There is a new pool join rule in xapi: the joining host may only have physical PIFs, i.e. no bonds, VLANs and tunnels (cross-server private networks). This is checked by asserting that for all PIFs of the joining host, PIF.physical = true. When this occurs, people should be encouraged to manually remove any existing bonds, VLANs or tunnels and try again.
=> CA-198767: Add only-physical-PIFs pool-join constraint

XenAdmin/HomePage.ja.mht, XenAdmin/HomePage.mht, XenAdmin/HomePage.zh-CN.mht, XenAdmin/HomePage/index.html
Now the Mhtml file contains the missing image as well. I used IE to save it and apparently (like other browsers) it does not save css-specified background images, so had to add a 0x0px sized img into the html to make IE to save it. Easy workaround and no change to the layout.
=> CA-199145: Home page missing the page icons that are used as list bullets

XenAdmin/Actions/GUIActions/Wlb/WlbOptimizePoolAction.cs, XenAdmin/Commands/VMOperationCommand.cs
- The StartDiagnosisForm dialog shows the reasons why a VM cannot be started or resumed. XenCenter tries to get these reasons from a call to VM.assert_can_boot_here, but his function does not perform a CPU feature compatibility check.
- This commit adds the CPU feature compatibility check for resume operations.
=> CA-196643: Check the CPU feature compatibility in StartDiagnosisForm

XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx
=> CA-202076: Some logs in Server Status Report don't have description

XenAdmin/SettingsPanels/VMAdvancedEditPage.Designer.cs, XenAdmin/SettingsPanels/VMAdvancedEditPage.cs, XenAdmin/SettingsPanels/VMAdvancedEditPage.resx, XenAdmin/Wizards/NewVMWizard/Page_Name.ja.resx, XenAdmin/Wizards/NewVMWizard/Page_Name.resx, XenAdmin/Wizards/NewVMWizard/Page_Name.zh-CN.resx
- Changes to the the layout: order of radio buttons, removed group box around the manual setting of shadow multiplier;
- Shadow multiplier edit box no longer disabled when "Optimize manually" not checked
- Also changed the wording on the Name page of the new VM wizard
=> CA-202371: Change wording on VM Advanced options page

XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs
When an exception is reported during the RPU, XenCenter tries to re-enable the host. But when this fails, we should just ignore it and report the original exception.
=> CA-205204: Uncaught exception during RPU

XenModel/Actions/SR/SrReattachAction.cs
Set the name and description of the SR after the PBDs have been created and plugged.
=> CA-205199: Reattaching an SR fails with error "The SR is not attached"

XenModel/XenAPI-Extensions/VM.cs
Check different feature flag for Windows VMs on Dundee to detect Dundee guest agent. For earlier versions nothing is changed.
This will cause XC to report "Management not installed" for Windows VMs on Dundee hosts with Cream guest agent (This is the case when a host has been upgraded from Cream to Dundee).
=> CA-202374: XC greyed out 'Install Tools' menu for imported VM from Cream

XenAdmin/Dialogs/VMProtectionRecovery/PolicyHistory.cs, XenAdmin/Dialogs/VMProtectionRecovery/VMProtectionPoliciesDialog.cs, XenModel/Actions/VMSS/GetVMSSAlertsAction.cs, XenModel/XenAPI-Extensions/VMSS.cs, XenModel/XenAPI/VM.cs
XAPI expects "OpaqueRef:NULL" in the value field to unassign a VM from
a particular policy, however XC is sending an empty string "". As a fix
the empty string is replaced with Helper.NullOpaqueRef.
=> CA-198956: VM.set_snapshot_schedule throws exception "Object deleted: VMSS" in xapi

XenAdminTests/UnitTests/HealthCheckAnalysisProgressTest.cs, XenAdminTests/XenAdminTests.csproj, XenModel/Actions/HealthCheck/GetHealthCheckAnalysisResultAction.cs
- Try to get the analysis progress from cis (as an integer value representing percentage 0 - 100). If this function returns a valid progress less than 100, then we don't try to get the report analysis and continue to display "Analysis not yet available"
- If the progress is 100 then we get the analysis result and display it
- If the progress cannot be obtained, then we try to get the analysis result; If an empty result is obtained within 10 minutes from the upload completion, then we assume that the analysis is still in progress and continue to display "Analysis not yet available"
=> CA-206761: Health Check shows "No issues found" when the report analysis is not yet available

XenAdmin/Wizards/NewSRWizard_Pages/Frontends/VHDoNFS.Designer.cs, XenAdmin/Wizards/NewSRWizard_Pages/Frontends/VHDoNFS.cs, XenAdmin/Wizards/NewSRWizard_Pages/Frontends/VHDoNFS.resx
- Re-position the version radio-buttons, so that is clear that the selected version applies to both Create and Reattach
- Pass the selected version to the attach command in the device_config parameter
=> CA-208495: XenCenter does not specify the NFS version when reattaching an existing SR

XenAdmin/Controls/ComboBoxes/VgpuComboBox.cs
The error occurs when there is a gpu group with only one vgpu type: When setting the selected item in the vGPU combobox, XenCenter tries to select the group header instead of the vGPU type; because the group header is not selectable, we then default to "None".
With this fix, we ensure that two items are not equal if one is a group header and the other is a subitem.
=> CA-210732: XenCenter VM properties GPU always shows "None"

XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
DownloadUpdatesXmlAction is now called on PageLeave and not when the user selects Automatic Mode. This way we get the error message at the right time, also showing a progress dialog what makes the UX much better.
New tooltips for servers on the Select Server Page to to cover two more cases
=> CP-15714: UI: Change Select Servers Page

XenAdmin/TabPages/GeneralTabPage.cs
=> CA-209290: "Virtualization state" label displayed twice on General Tab of newly created VM

XenModel/Actions/AD/EnableAdAction.cs
Calling disable on a best effort basis. (We always call disable AD before enabling AD -  CA-48122)
=> CA-187187: Enable AD on pool failing when one of the hosts have failed

XenAdmin/Controls/GPU/GpuRow.cs
The last pGPU's row was stretching to the bottom, causing the lowest select box to fill its space and go down too much.
Changed the select boxs' dock style and margin.
Signed-off-by: Frederico Mazzone <fredericom@citrite.net>
=> [CA-207306] Select box is not in line with pGPU bar on GPU tab of host

XenAdmin/Dialogs/PropertiesDialog.cs, XenModel/XenAPI-Extensions/Host.cs
- For Dundee and newer hosts: the feature is restricted only if the "restrict_ssl_legacy_switch" flag exists and it is set to true
- For pre-Dundee hosts: the feature is restricted if the "restrict_ssl_legacy_switch" is absent or it is present and set to true
=> CA-213414: Check feature-flag for ssl-legacy control switch

XenAdmin/Core/WebBrowser2.cs, XenAdmin/Dialogs/DownloadApplianceDialog.cs, XenAdmin/Plugins/Features/TabPageFeature.cs, XenModel/Actions/HealthCheck/GetHealthCheckAnalysisResultAction.cs, XenModel/Actions/HealthCheck/HealthCheckAuthenticationAction.cs, XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs, XenOvfTransport/Import.cs
Assigned Proxy property in all WebClient, WebRequest and HttpWebRequest instances.
Removed "proxy not supported" message from Download Appliance dialog, since the download does work with a proxy.
=> [CA-213410] XenCenter ignores proxy settings in some places

XenAdmin/Commands/DeleteFolderCommand.cs, XenAdmin/Commands/DragDropIntoFolderCommand.cs, XenAdmin/Commands/NewFolderCommand.cs, XenAdmin/Commands/RemoveFromFolderCommand.cs, XenAdmin/Commands/RenameFolderCommand.cs, XenModel/Actions/Folders/FolderAction.cs, XenModel/Folders.cs
- Changed the FolderAction class so that it can be used to delete or move multiple folders across connections, instead of having multiple actions (one for each holder) which can not run in parallel.
- The api calls that update the EMPTY_FOLDERS entry in pool's other_config are preformed last for all connections, avoiding cross-thread exceptions when two threads try to add/remove the same key.
=> CA-209502: Exception while deleting multiple folders

XenAdmin/Wizards/PatchingWizard/PatchingWizard_AutoUpdatingPage.cs
Where (in code removed by this commit) we iterated through the planActionsByHost dictionary, the hosts were iterated through in the order how the dictionary was initialized. Despite the actions were added in the right order, the result was screwed up, because the Cache.Hosts list can have the hosts randomly while we want the master to be first.
To fix the bug, I changed the data structure from a dictionary to a list that has the actions exactly in the good order, the order they were added, eliminating the risk of the actions being retrieved in the wrong order.
=> CA-215093: Batch updates: Update progress failed in a pool of mixed state hosts

XenAdmin/Core/Registry.cs, XenAdmin/Dialogs/OptionsPages/ConnectionOptionsPage.cs, XenAdmin/Program.cs
Added Registry.ProxyAuthenticationEnabled boolean property to enable/disable proxy authentication UI controls in Connection Options page.
Cleaned up event handler logic in Connection Options page to return from multiple/unnecessary calls to event handlers when manually changing controls through code.
=> CP-17933: Add feature flag for proxy authentication

XenAdmin/Dialogs/ConnectingToServerDialog.cs, XenAdmin/Network/XenConnectionUI.cs
ConnectingToServerDialog now keeps track of the dialogs for each connection and focuses on them if they already exist, instead of creating new ones.
=> CA-214953: Multiple connection dialogs while attempting to connect

XenAdmin/SettingsPanels/Wlb/WlbAutomationPage.cs
"listViewExPowerManagementHosts_ItemCheck" will be called both navigating to Automation tab and user click the checkbox. 
This change makes to remember the uuid when navigating to Automation tab, not to show warning dialog.
Signed-off-by: Liang Dai <liang.dai1@citrix.com>
=> CA-144951: [WLB Settings] Multiple pop-ups when navigating to Automation tab.

XenModel/Messages.Designer.cs, XenModel/Messages.resx
Changed confusing message from "Removing update ..." to "Removing update file ...".
=> CA-214622: XenCenter Install update Wizard Confusing Info shown on Install update screen

XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.Designer.cs, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.cs
Bugs fixed:
* OK button not re-enabling when switching back to using existing credentials in Health Check Enrollment dialog
* Using empty credentials to authenticate with Citrix Insight Services does not disable OK button in Health Check Enrollment dialog
=> CA-213281, CA-213278: OK fixed

XenAdmin/Wizards/PatchingWizard/PatchingWizard_PatchingPage.cs, XenModel/Actions/Pool_Patch/ApplyPatchAction.cs
XenCenter no longer ignores checking if the master host already has the specified patch applied; it now checks before trying to apply it, which means we get no error in the Patching Wizard's Patching Page.
=> CA-209198: Allowed to attempt to install hotfix when it is already applied

XenAdmin/Controls/AffinityPicker.Designer.cs, XenAdmin/Controls/AffinityPicker.cs
Even though the correct row have been selected by the time the grid becomes visible, it is not displayed properly. This change set fixes the problem by selecting the row again.
=> CA-213728: Going to Home Server tab can change home server

XenAdmin/TabPages/SnapshotsPage.cs
vmss snapshots are shown even when Scheduled snapshots is
unchecked in same menu.
=> CA-213499: List view of snapshots not working as expected with VMSS

XenModel/Messages.resx
Changed message to "Deleting update installation file ..." to match wording in previous page of the wizard.
=> CA-214622: Confusing info shown on Install Update screen

XenAdmin/Controls/XenSearch/SearchOutput.resx
New hotkey for "Show columns" is alt+C
=> CA-150200: EN: Duplicate hotkeys for “Storage” and “Show Columns” under Citrix XenCenter.

XenAdmin/Controls/XenSearch/SearchOutput.resx
Remove the old value, leaving only the new one
=> CA-150200: EN: Duplicate hotkeys for “Storage” and “Show Columns” under Citrix XenCenter

XenAdmin/Core/Updates.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs, XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs, XenModel/Actions/Updates/XenServerVersion.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
If there is no <minimalpatches /> tag, the version is not supported. This check has priority over licensed state when displaying the reason why a server is not supported.
=> CA-217844: Handling Automatic update not supported

XenModel/Actions/MultipleAction.cs, XenModel/Actions/ParallelAction.cs
- The multiple action is cancellable if is at least one sub action is not completed
- When a multiple action is cancelled, we try to cancel all sub actions that are not completed
- Also changed the way we calculate the percent complete for the parent action, to report partial progress of the sub actions
=> CA-210549: Make MultipleAction and ParallelAction cancellable

XenAdmin/Core/Updates.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs, XenAdminTests/UnitTests/BatchUpdatesTests/BatchUpdatesTests.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Partially upgraded pools and mixed version pools are not supported, XenCenter will display a proper error message.
=> CA-217862: Batch Updates: handle partially upgraded pools

XenAdmin/TabPages/SnapshotsPage.cs
CA-213500: Revert To, Actions and Delete buttons are enabled even
if there is no manual snapshot.
=> CA-213500: Revert To, Actions and Delete buttons are enabled even if there is no manual snapshot.

XenAdmin/Dialogs/PropertiesDialog.cs, XenAdmin/SettingsPanels/LivePatchingEditPage.Designer.cs, XenAdmin/SettingsPanels/LivePatchingEditPage.cs, XenAdmin/SettingsPanels/LivePatchingEditPage.ja.resx, XenAdmin/SettingsPanels/LivePatchingEditPage.resx, XenAdmin/SettingsPanels/LivePatchingEditPage.zh-CN.resx, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.ja.resx, XenModel/Messages.resx, XenModel/Messages.zh-CN.resx, XenModel/XenAPI-Extensions/Host.cs
Add a live patching tab with a checkbox to toggle whether live patching is allowed for a licensed pool or standalone host.
=> Cp 18011: [XenCenter] Add live patching checkbox

XenAdmin/Commands/DisconnectCommand.cs
The CancelHostConnectionCommand executes by using a DisconnectCommand, so the fix here is to allow that command to execute on connections in progress as well as those that are connected.
=> CA-218241: Cancel connect right click menu item does not seem to be doing anything

XenAdmin/TabPages/SrStoragePage.resx
=> CA-150198: EN: Missing hotkey for “Properties” after right clicking virtual disk

XenAdmin/SettingsPanels/PerfmonAlertEditPage.Designer.cs, XenAdmin/SettingsPanels/PerfmonAlertEditPage.resx
This is resolved by moving the label into a TableLayoutPanel, docked to the top and with auto-grow on.
=> CA-218304: Text cut off in Properties dialog, Alerts tab

XenAdmin/SettingsPanels/HomeServerEditPage.cs
By passing null as the srHost parameter to the affinity picker, the "no home server" radio button remains enabled, even when no shared SRs are available, allowing users to unset the home server of a VM
=> CA-180127: Unable to unset VM home server if all shared SRs are full

XenAdmin/Images.cs
Snapshots taken part of VMSS have same symbol as manually taken snapshots in saved snapshot searchas manually taken snapshots in saved snapshot search
=> CA-213496: Snapshots taken part of VMSS have same symbol as manually taken snapshots

XenAdmin/Commands/InstallToolsCommand.cs, XenModel/Actions/VM/InstallPVToolsAction.cs, XenModel/Network/XenConnection.cs, XenModel/XenAPI-Extensions/VDI.cs
- when the cd drive or the tools iso cannot be found, the action should fail.
- if the tools SR is broken, do not show the error on a pop-up because the UX is
bad when installation is attempted on multiple VMS.
- added one more entry to the list of possible tools iso names.
- small performance improvement.
=> Improvements made while investigating CA-218953:

XenAdmin/SettingsPanels/CustomFieldsDisplayPage.cs, XenAdmin/TabPages/PerformancePage.cs
The ticket said the character after the & became a hotkey (like labels etc do with UseMnemonic enabled) but I couldn't reproduce that - & symbols were simply removed from the string. The fix is to replace them with &&, so the string.format prints a single & as it should.
=> CA-140181: Inconsistent name displaying when it contains symbol '&’

XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs, XenAdmin/Diagnostics/Checks/PatchPrecheckCheck.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizardModeGuidanceBuilder.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PatchingPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdminTests/WizardTests/PatchingWizard/PatchingWizardModeGuidanceBuilderTests.cs
This commit implements the check for LiveUpdate capability of a patch. If
the patch is completely live-updatable, XenCenter will not restart the
host (but will do further checks once it has finished installing the
update - separate ticket)
=> CP-18012: Use extended precheck information in Update Wizard

XenAdmin/Wizards/PatchingWizard/PatchingWizard_PatchingPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/StringExtensions.cs
If we are expecting to live patch, but at the end
hosts.patches_requring_reboot contains the patch, then warn the user that
live patching has failed for the host - and it needs to be rebooted.
=> CP-18618: If live patching fails, warn the user

XenAdmin/TabPages/SrStoragePage.cs
Change the sorting on the Name and Description columns to use StringUtility.NaturalCompare, which correctly sorts strings with numbers at the end (eg name, name0, name1, name2, name10 will now sort correctly while alphabetic sorting is incorrect). Also added a tie break on uuid to make sorting behave predictably with duplicates in these columns.
=> CA-112317: Sorting on SR storage tab is incorrect

XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeReadyToUpgradePage.cs
Ellipsised pool and host names on the Ready to Upgrade page to 64 characters, which resolves the layout problem from extremely long names.
=> CA-107341:  Truncation issue occurred on rolling pool upgrade window.

XenAdmin/Controls/XenSearch/QueryElement.cs
The truncating of the custom field name by space (instead of ellipsising) seems to be a Windows default, but it's not ideal. This change edits the text displayed in the dropdown when an item is selected so that if a custom field is selected it is ellipsised to an appropriate length. It doesn't affect the dropdown itself, which continues to display the full custom field name.
=> CA-140338: Truncation on New Search Page with long Custom Field Filters name

XenAdmin/Wizards/PatchingWizard/PlanActions/EvacuateHostPlanAction.cs
This fixes the NullReferenceException that occurs when trying to evacuate a host after a non-livepatch update (that requires reboot) has been installed
=> CA-220049: Non-livepatch hotfix installation is failing

XenAdmin/Wizards/PatchingWizard/PatchingWizardModeGuidanceBuilder.cs, XenModel/Actions/ParallelAction.cs
**CA-220040: Patching wizard shows reboot required where it is not expected**
- When building the list of servers that require post-install actions, ignore the ones where the patch has already been installed.
- Also fixing the infinite recursion in Build() method (causing StackOverflowException when installing a supplemental pack).
**Fix an error in ParallelAction with no subactions**
- Immediately complete the ParallelAction when there are no subactions to be executed, to avoid on infinite lock while waiting for the actions to be completed.
=> CA-220040: Patching wizard shows reboot required where it is not expected

XenAdmin/Actions/GUIActions/ExportResourceReportAction.cs, XenAdmin/Commands/Controls/ContextMenuBuilder.cs, XenAdmin/Controls/NetworkingTab/NetworkList.cs, XenAdmin/SettingsPanels/EditNetworkPage.cs, XenAdmin/Wizards/ImportWizard/ImportWizard.cs, XenAdmin/Wizards/ImportWizard/NetworkPickerPage.cs, XenAdmin/Wizards/NewVMWizard/Page_Networking.cs, XenModel/XenAPI-Extensions/Network.cs
Expose both the HIMN network and any VIFs associated with the HIMN
network using XenCenter when the "View->Show Hidden Objects" option
is displayed. However the shown HIMN should not be able to autoplug,
edit or delete.
=> CA-218956: Expose HIMN when showing hidden objects

XenAdmin/Wizards/PatchingWizard/PatchingWizard_PatchingPage.cs
Fixed regression caused by 5555709337d60c9c786d7058fb2f8100982c4b5e.
Supplemental packs can now be installed again in automatic mode.
=> CA-220599: Supplemental Pack installed via XenCenter does not get listed in updates box

XenAdmin/Dialogs/ActionProgressDialog.cs
The bad message was in the dialog created in the BugToolWizard after selecting servers. Since this method is the only one using the ActionProgressDialog(String) constructor, I've modified that ctor to hide the subaction label - which makes sense because there is no action in that ctor (to set a subaction) and no other appropriate label.
=> CA-219777: Bad progress dialog message

XenAdmin/Wizards/GenericPages/HomeServerItem.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
We already renamed the column to target server, this changes the message in the case where the user doesn't choose a server on this page to also use target server.
Previous issue: #1119 
=> CA-217821: Renaming home server to target server in VM migration wizard

XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
Reverts xenserver/xenadmin#1169
Unhide Batch hotfixing
=> Revert "CP-18925: Hide batch hotfixing option in XenCenter"

XenModel/Actions/VM/VMSnapshotRevertAction.cs, XenModel/XenAPI-Extensions/VM.cs
Where we have a host the VM is running on (ie vm.resident_on is not null) at the time it is reverted, attempt to start/resume on that host if possible, instead of the home server of the VM.
=> CA-218260: Reverting to Snapshots causes VM to go back to parent host

XenAdmin/TabPages/SrStoragePage.Designer.cs, XenAdmin/TabPages/SrStoragePage.cs, XenAdmin/TabPages/SrStoragePage.resx
- show/hide the context menu items instead of creating and adding new ones each time the context menu opens
- right click menu with rescan/add was not available for empty list or when empty space was clicked
- the condition for the edit button was slightly different from the edit toolstripmenuitem
- improved button layout (part of CA-100083)
- tidied up button event handlers and renamed one or two class members
- removed unused parameter in constructor and method of VDIRow
=> Did some work on the SrStoragePage:

XenAdmin/MainWindow.cs, XenModel/Utils/Helpers.cs, XenModel/XenAPI-Extensions/SR.cs
- Show the PVS tab only when the supplemental pack is installed 
- Hide memory SR in XenCenter
=> CP-17920: Show the PVS tab only when the supplemental pack is installed & Hide Memory SR

XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs
Replace PATCH_PRECHECK_LIVEPATCH_MISSING to PATCH_PRECHECK_LIVEPATCH_NOT_APPLICABLE due to changes in XAPI
Note: if XAPI change gets active before this change we will see UNKNOWN instead of PATCH_PRECHECK_LIVEPATCH_NOT_APPLICABLE in XenCenter what will make no difference
=> CA-223082: Replace PATCH_PRECHECK_LIVEPATCH_MISSING

XenModel/Network/Heartbeat.cs
Normally, a heartbeat is done every 15 seconds by getting the server time, and starts as soon as connection to host is established, but if an error occurs XC retries once more in another 15 seconds before actually closing the connection to the host.
Now, if a 407 Proxy Authentication Required error occurs on the initial heartbeat then XC does not retry again in 15 seconds; it will close the connection immediately. The disconnection was instant to up to 2 seconds, depending on time taken to get server time (testing with FreeProxy was ~instant and CCProxy was ~2 seconds). This is only a work-around, as the exact reason for this behaviour is still unknown.
=> CA-214653: Work-around for XC reconnecting to proxy server with new wrong credentials

XenAdmin/Dialogs/AttachDiskDialog.cs, XenAdmin/Wizards/GenericPages/SelectVMStorageWithMultipleVirtualDisksPage.cs, XenModel/XenAPI-Extensions/SR.cs
- We shouldn't include the hidden SRs in the list of available SRs in the Migration wizard
- Updated the SR.SupportsVdiCreate function to return false for the Memory SR; this fixes other places where the Memory SR might be visible (e.g. all places where SrPicker is used)
- Also fixed the same issue in the  Attach disk dialog
=> CA-225015: XenCenter Allows VM migration to MemorySR

XenAdmin/Dialogs/OptionsPages/ConnectionOptionsPage.Designer.cs, XenAdmin/Dialogs/OptionsPages/ConnectionOptionsPage.cs, XenAdmin/Dialogs/OptionsPages/ConnectionOptionsPage.resx, XenAdmin/MainWindow.cs, XenAdmin/Program.cs, XenAdmin/Properties/Settings.Designer.cs, XenAdmin/Properties/Settings.settings, XenAdmin/app.config, XenModel/Actions/HealthCheck/TransferProxySettingsAction.cs, XenModel/Network/HTTPHelper.cs, XenModel/XenAPI/HTTP.cs, XenServerHealthCheck/Properties/Settings.Designer.cs, XenServerHealthCheck/Properties/Settings.settings, XenServerHealthCheck/ServerListHelper.cs, XenServerHealthCheck/XenServerHealthCheckService.cs, XenServerHealthCheck/app.config
2 new radio buttons in Connection Options page, for Basic and Digest; Digest is the default as it's the most secure.
New proxy authentication method setting, which is used to configure XenAPI's HTTP class and the .NET AuthenticationManager (which handles which authentication schemes can be used by the .NET web classes).
The new setting is also transferred and used by the Health Check service.
The bug noted in CA-214653 also occurs here, but the work-around on PR#1201 for that bug will also work for this.
=> CP-19111: Added ability to choose Basic or Digest authentication for proxy server

XenAdmin/Controls/PvsCacheStorageRow.cs, XenAdmin/Dialogs/AttachDiskDialog.cs, XenAdmin/TabPages/PvsPage.cs, XenAdmin/Wizards/GenericPages/SelectVMStorageWithMultipleVirtualDisksPage.cs, XenModel/XenAPI-Extensions/SR.cs
- instead of repopulating the whole grid when a proxy or a site changes, we now refresh just the row that needs refreshing, and when the refresh is indeed needed.
=> CA-224666: Things in PVS tab constantly refreshing

XenAdmin/Dialogs/ControlDomainMemoryDialog.cs
- take the already assigned dom0 memory into account when calculating maximum memory available
=> CA-225708: Can not increase dom0 Memory multiple times

XenAdmin/Commands/ActivateVBDCommand.cs, XenAdmin/Commands/DeactivateVBDCommand.cs
Instead we use the vbd.allowed_operations list, and check for the plug/unplug operation respectively.
=> [CA-225062] For Ely and greater hosts, don't check for IO tools when activating/deactivating (this covers detatch + delete too in UI) a VBD

XenAdmin/Actions/OVFActions/ApplianceAction.cs, XenAdmin/Actions/OVFActions/ExportApplianceAction.cs, XenAdmin/Actions/OVFActions/ImportApplianceAction.cs, XenAdmin/Actions/OVFActions/ImportImageAction.cs
For other actions we get a ticking timer in the Events view because they use PollToCompletion, which calls their Changed event (via Action.Tick) every 900ms. These actions don't use PollToCompletion, and didn't regularly call their Changed event - so their timer didn't tick regularly. This change adds a lightweight mechanism to call their changed event every 900ms until they complete. This allows the events page timer to tick every second in the same way as it does for other actions.
=> [CA-211267] Add a lightweight polling mechanism to the appliance tasks, to provide an accurate timer

XenAdmin/Controls/CustomDataGraph/DataSet.cs, XenAdmin/Controls/CustomDataGraph/GraphHelpers.cs, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx, XenModel/Utils/Helpers.cs
We have some new RRDs - read, write, read_latency and write_latency. This adds support for them by adding a friendly name and using it to display them. It also adds some filtering (see GraphHelpers.cs) because for backward compatibility io_throughput_read and io_throughput_write (which differ from read and write only in scale) are still available, but shouldn't be displayed in XC. If the new read or write are available, we filter these old datasources out.
=> [CA-220457] Add friendly names for new graphs, and filter duplicates

XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
We now only include the StorageLink check if we have any hosts earlier than Creedence in the RPU.
=> [CA-223486] Storage Link Status validation is wrongly included in Precheck During RPU

XenAdmin/TabPages/GeneralTabPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
On the General tab XenCenter shows a list of updates that requires the host to be restarted. This is shown for applied updates for which the required guidance hasn't been done (eg. restartHost or restartAgent after-apply-guidances)
This commit fixes a regression that caused restartToolstack warnings to be not shown in the list of warnings.
The displayed messages are also improved, XenCenter will show Toolstack restart or host restart appropriately and not just restart only as it used to.
=> CA-227067: General tab: XenCenter does not show Reboot required when Toolstack restart is required

XenModel/Actions/VM/VMMoveAction.cs
A VM can find itself with a VBD with an unresolved VDI (e.g. ejected CD). The VDI will not have been included in the storage mapping and the user will be presented with a KeyNotFoundException message even if the move of the other VDIs has succeeded. To fix this ignore unresolved VDIs first, then check 
if the storage mapping contains the resolved ones and then try getting the target SR from the mapping.
=> Avoid KeyNotFoundException when moving VMs with unresolved VDIs

XenAdmin/Core/HiddenFeatures.cs, XenAdmin/TabPages/GeneralTabPage.cs
If windows_update is in the hidden features registry key, then we hide the virtualization state line about Windows update.
=> [CA-226116] Add Windows update as a hidden feature

XenAdmin/Dialogs/PvsCacheConfigurationDialog.cs, XenAdmin/Dialogs/PvsCacheConfigurationDialog.resx, XenAdmin/Dialogs/PvsPages/PvsCacheConfigurationPage.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- show a different message when deleting a Cache Configuration (a PVS_site object) that is actively in use by a PVS site
- some more text changes on the "Configure PVS Cache" dialog
=> CA-227072: Improvements to the confirmation message on deleting a site

XenAdmin/TabPages/GeneralTabLicenseStatusStringifier.cs
The problem here was that TimeSpan.Minutes is always below 60, eg. for 67 minutes it is 7 (with TimeSpan.Hours being 1 then). So our TimeSpan was correct, but if it was between 1 and 2 hours then we would write the minutes in the second hour (which is below 60), ignoring the hour. The fix is to use s.TotalMinutes which for 67 minutes is 67. Hours also had a similar issue, except it would be off by 24 hours for spans between 1 and 2 days.
=> [CA-207601] License expiry time in general tab is incorrect

XenAdmin/Commands/NewVMCommand.cs
The reported bug was that the new VM would crash because when clicking through the wizard the pool master is selected by default, not the slave the VM snapshot is on. We already select a default host when a new VM is created from a selected host using HostAncestor, but this property is null for a template (which isn't in the server/VM tree). The fix is that if the selection is a template (which it is when we use new VM from Snapshot) then we instead use its host (using Home()) as the default host. Now the correct host is selected in the VM wizard and the VM creation succeeds.
=> [CA-203752] New VM from Snapshot doesn't use default host

XenModel/Messages.Designer.cs, XenModel/Messages.resx
=> CA-227067: General tab: XenCenter does not show Reboot required when Toolstack restart required

XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.Designer.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.resx
I've looked at how this was implemented in Dundee, and there we used an absolute height on the row containing the manual checkbox. I've done the same here, changing row 3 from autosize to absoliute 47px. I've also removed the empty row that was between the two radio buttons. This is a Winforms problem, without workarounds an autosize radio button in an autosize container (say the table row) will report its height as one row of text, no matter whether it needs more. This seems to be the only place we use a long radio label (as opposed to a separate label underneath the radio), so I doubt it's worth doing anything more complex than this. I've tested it with the CN string used in the ticket, and it uses less space than the English translation. The string also hasn't changed from Dundee. …
=> [CA-227602] Truncation on the Install Mode page in the Install Upgrade wizard

XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.ja.resx, XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.zh-CN.resx
This change is to change CN and JP process_lable height same as EN version
=> CA-227274: Fix CN and JP version process lable size

XenAdmin/Controls/CustomDataGraph/GraphList.cs
(not current vcpus)
Instead of using VCPUs_max, use VCPUs_at_startup, which is the value set when we change the VCPUs count on the VM. Note that despite its name we don't need to restart to see this value change.
=> [CA-225715] Performance Graph reporting for CPU for a VM based on max VCPUs

XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.Designer.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_ModePage.resx
Due to the tooltip container introduced for the automatic radio button, winforms didn't treat these radio buttons properly - we needed code to make them mutually exclusive, tab didn't behave properly and keyboard arrow navigation between them didn't work. Therefore I have removed the tooltip container (so our radio buttons behave properly without any extra work) and we instead use a winforms tooltip shown when the mouse is over the automatic radio button. Note that since the control is disabled when we want a tooltip, neither hover events nor attaching a winforms tooltip in the usual way will work. Therefore I use a mousemove event on the table, which displays the tooltip if and only if we are over the disabled control. 
Also adjusted the tab indexes to make sure tab works correctly …
=> [CA-227845] Fixing problems caused by tooltip container on hotfix wizard mode page

XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs
This happened because the LivePatchCodesByHost was null when the prechecks were generated for an update, so the live patch codes returned by the precheck were ignored.
=> CA-227034: Slipstream packaged Live patching hotfix is rebooting host

XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs, XenAdmin/Commands/CrossPoolMigrateCommand.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateWizard.cs, XenModel/Actions/VM/VMCrossPoolMigrateAction.cs
The resume on server uses the CrossPoolMigrateCommand to implement the migration of the VM to the desired host. Before this change that command had no support for resuming a VM after migrating it, so the VM was not resumed. With this change, the CrossPoolMigrateWizard can take an optional (default false) parameter to restart the VM after migration. When this is true, the migrate action becomes a MultipleAction, first migrating and then restarting the VM.
=> [CA-226897] Resume on Server option won't automatically resume the VM

XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs
Modify the cleanup pool update action to also call update destroy (removing the update from xapi db) when the update has not been applied to any hosts (ie we cancelled the wizard before completion).
=> [CA-228723]  Cancelling update installation leaves the update in xapi db

XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs
For ISO updates, when disabling hosts, use the filename matching logic for pre-Ely hosts as well.
=> CA-229185: XenCenter: Dundee and Creedence hosts should be disabled for Ely updates in 'Select Servers'

XenAdmin/Dialogs/PropertiesDialog.cs, XenAdmin/Wizards/NewPolicyWizard/NewPolicySnapshotTypePageSpecific.cs
Enabling snapshot policy type to be changed to quiesce from other snapshot policy types if the selected VMs are quiesce snapshot capable.
Signed-off-by: Sharath Babu <sharath.babu@citrix.com>
=> CA-213563: VM policy cannot be changed to snapshot with quiesce after installing vss tools

XenAdmin/Dialogs/GraphDetailsDialog.cs
Replace the string comparison used when sorting columns of the datasources list table with a natural compare, which sorts these cases correctly.
=> [CA-228054] Performance graph datasources aren't sorted naturally

WixInstaller/XenCenter.wxs
Per the ticket, the solution is to remove the tooltip, which is set by the description on the shortcuts.
=> [CA-153567] Hardcode of “XenCenter Shortcut” in All Programs list.

XenAdmin/Controls/ComboBoxes/EnableableComboBox.cs, XenAdmin/Dialogs/EnablePvsReadCachingDialog.Designer.cs, XenAdmin/Dialogs/EnablePvsReadCachingDialog.cs, XenAdmin/TabPages/PvsPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/PVS_site.cs
We now disable sites that aren't configured in the enable read caching dialog, using an EnableableComboBox. I've also changed the DrawMode of that ComboBox component, OwnerDrawFixed more appropriately sizes the dropdown container when the number of items is small.
=> [CA-228051] XenCenter allows user to create unusable PVS Proxy cache config

XenAdmin/Controls/ComboBoxes/EnableableComboBox.cs, XenAdmin/Controls/PvsCacheStorageRow.Designer.cs, XenAdmin/Controls/PvsCacheStorageRow.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
We now disable the Memory Only option if the available dom0 memory is less than the minimum the spinner supports (1Gb)
=> [CA-229350] PVS allows Memory Only even when no control domain memory available

XenAdmin/Wizards/PatchingWizard/PatchingWizard_AutoUpdatingPage.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/RemoveUpdateFilesFromMaster.cs, XenModel/Actions/SupplementalPack/UploadSupplementalPackAction.cs
If batch updating fails in a pool, this code will do the clean up by running the appropriate (next in the queue) RemoveUpdateFilesFromMaster action. In addition to Pool_update.clean(), Pool_update.destroy() will be called when needed.
=> CA-229009: VDI is not deleted for the updates

mk/package-and-sign.sh
Use executables from WIX_BIN instead of the default Wix candle/lit/light exes
=> CA-233286: Error while running the package-and-sign script

XenAdmin/TabPages/AlertSummaryPage.resx, XenAdmin/TabPages/HistoryPage.resx, XenAdmin/TabPages/ManageUpdatesPage.cs, XenAdmin/TabPages/ManageUpdatesPage.resx
Moved to A for Dismiss All, and E for Dismiss Selected. Since this frees D (the toolstrip menu split button uses one of these, so was previously always D), moved Filter by Date from A to D.
=> [CA-149812] EN: Duplicate hotkeys about “Dismiss All” and “Dismiss Selected" tabs.

XenAdmin/TabPages/PvsPage.cs
Changed the collection handlers to use ProgramInvokeHandler in the same way as other tabs, instead of Program.Invoke which caused the hang.
=> [CA-232963] XC hangs after restarting toolstack while viewing PVS tab

XenAdmin/Dialogs/AddServerDialog.Designer.cs, XenAdmin/Dialogs/AddServerDialog.cs
This commit is to fix the following: "when right clicking a disconnected pool the context menu gives you the option to connect, this opens a window to enter credentials. if you close this window (either by cancel or the X), next time when you right click and click connect, nothing happens. you have to restart XenCenter to connect to the pool"
=> CA-232294: Can't connect if an Add Server dialog has been cancelled before

XenAdmin/TabPages/PvsPage.cs, XenModel/Actions/VM/CreateVMAction.cs, XenModel/Actions/VM/CreateVMFastAction.cs, XenModel/Utils/Helpers.cs, XenModel/XenAPI-Extensions/VM.cs
Refined the rules for not adding a VM to the table, if it is a template (thus not_a_real_vm), and it has the __gui__ prefix (thus hidden), we still add it, but hide it.
When its name is changed (to remove the __gui__ prefix), we update its name and re-calculate whether it should be visible (in the case of a new VM this will be true once the __gui__ prefix is gone). Also resort the table if a node changes from hidden to visible, because it appears as an addition to the table.
=> [CA-233454] PVS tab doesn't show a new VM when it's created

XenAdminTests/XenModelTests/ActionTests/VMActionsTest.cs, XenModel/Actions/VM/CreateVMFastAction.cs
Added an extra parameter to the CreateVmFastAction constructor, which is used to specify whether to set the VM's property IsBeingCreated. In order to set this property, we need to wait for the newly created VM to appear in the cache. But we cannot do this in the action test, because the cache is not being updated. Therefore the action needs skip this step when running from the tests. The IsBeingCreated property is only used in the UI, to refresh the PVS tab after the VM is created, so the accuracy of the action test (CreateVMFastActionTest) is not affected by this change.
=> CA-233454: Fix the action test

XenAdmin/Core/HealthCheck.cs
Set the suppressHistory flag to true for the parallel action that we run periodically to check the Health Check analysis result
=> CA-234628: Errors with no title in XenCenter

XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs
This change implements a lightweight retry logic for downloading updates to protect against temporary network issues.
=> CA-234638: XenCenter does not retry downloading: Workaround for temporary download problems

XenAdmin/Wizards/NewSRWizard_Pages/Frontends/CIFS_ISO.Designer.cs, XenAdmin/Wizards/NewSRWizard_Pages/Frontends/CIFS_ISO.cs, XenAdmin/Wizards/NewSRWizard_Pages/Frontends/CIFS_ISO.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
This commit implements the same logic that is used for NFS ISOs.
=> CA-207011: Don't allow XC to create more than one SMB ISO SR on the same share

XenModel/Actions/Pool_Patch/PoolPatchCleanAction.cs
Fixed a typo that caused XenCenter to show a Trace error dialog (and to fail to do the clean-up) after applying an update in manual mode. (only if RBAC is involved)
=> CA-236705: [XSO-662]: Applying Updates as Non-root Pool_admin user causes exception and crash of XenCenter

XenAdmin/Commands/CrossPoolCopyVMCommand.cs
Added a check for the vm's default_template as a workaround for an issue where the allowed_operations of a default template _initially_ indicated that cross pool migration was allowed.
=> CA-234494: System template cross-pool copy fails with Internal error:assert_can_migrate: inter_pool_metadata_transfer returned nonempty list

XenModel/Actions/SupplementalPack/UploadSupplementalPackAction.cs
Remove the VDI only on a best effort basis if the upload failed in the UploadSupplementalPackAction. This will make XenCenter to display the message from the original exception and not from the removal action if the latter had also failed.
=> CA-236566: test-hotfix-basic-7 throws error 'VDI is in use by some other operation'

XenAdmin/Diagnostics/Checks/PatchPrecheckCheck.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.cs
Fixing the error, so the hotfix installation will fail as and where it is expected
=> CA-236547: Unexpected error while applying hotfix on multiple Xenservers of different version

XenModel/XenAPI-Extensions/Host.cs, XenModel/XenAPI-Extensions/VM.cs
CA-237963: On a partially upgraded pool (from Dundee to Ely) the hosts lose their consoles
When getting the control domain VM, we should use the control_domain only if it is not null. there is no need to check the version (which was, however, looking at the API version of the master)
=> CA-237963 to release/ely/staging

XenAdmin/Commands/Controls/AssignVMGroupToolStripMenuItem.cs
[VMSS] XC -> right click 'VM' -> Assign VM to snapshot schedule shows all policies,
even though they are not supported by VM
=> CA-213505: Right click on a VM allows assignment to a policy of unsupported snapshot type

XenAdmin/Core/Updates.cs
These lists were continuously growing on each refresh, because the Where
clauses returned all items as the predicate was always evaluated to
true. The reason is: A. Even IEquatable<XenServerPatch> is
implemented on XenServerPatch, it only compares uuids. B. XenServerVersion
(also XenCenterversion) does not implement Equals (always different as the
Action returns new objects).
The two bugs these caused are: A] forever growing list of versions caused
obsolete data to be kept while everything was added to the end of the list
additionally. B] Any previously added Patch would not be updated unless the uuid had been changed (this never changes).
Fix in this commit: On each refresh, taking the new lists as they are
(from the Action) and not trying to keep or modify existing items. GC will do the …
=> CA-238993: Fixed: forever growing updates list while new or updated metadata was not shown

XenModel/Actions/VM/ImportVmAction.cs
For ElyOrGreater hosts, we try move the existing VIFs to the desired networks. We will only destroy and create new ones for older hosts or when a corresponding VIF cannot be found in the network mapping.
=> CA-238901: PVS proxy not setup for imported VM

XenAdmin/Alerts/Types/MessageAlert.cs
After deleting the schedule vmss will be null for that message, hence
we need to handle this case.
Signed-Of-By: Sharath Babu <sharath.babu@citrix.com>
=> CA-241844: [VMSS] Deleting a snapshot schedule raises XenCenter error

XenModel/Actions/VMPP/CreateVMPP.cs
A wrong api was being tested against the RBAC roles. Removed
vmss.protect_now and added vmss.snapshot_now.
Signed-Of-By: Sharath Babu <sharath.babu@citrix.com>
=> CA-241883: [VMSS] Pool Operator/Pool Admin - VMSS Policy creation raises an assertion error in XC

XenModel/Alerts/PolicyAlert.cs
When Text is null error is raised by split() function, we
need to handle that case.
=> CA-241847: [VMSS] VM Protection policies pop-up from Pool -> VM Protection policies raises XenCenter error on XS 6.1

XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs, XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs
Switched to use WebClient when downloading updates.xml
Fixed a bug where proxy settings were ignored when downloading updates
=> CA-241431: Using standard .net WebClient to download updates.xml

XenModel/XenAPI/HTTP.cs
Improved the ReadHttpHeaders function, by making sure that a chunk is read fully from the stream (the number of bytes read by the Stream.Read function can be less than the number of bytes requested, so we need to continue reading until the required number of bytes is read)
=> CA-242397: Fix format exception caused by incorrect chunk reading 

XenAdmin/Core/Registry.cs, XenAdmin/Dialogs/OptionsPages/ConnectionOptionsPage.cs, XenAdmin/Program.cs
The ProxyAuthenticationEnabled registry key is no longer needed since
CAR-2214 is now in its own branch.
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>
=> CP-20918: Remove proxy authentication registry key

XenAdmin/Dialogs/NetworkingProperties.cs, XenAdmin/Dialogs/NetworkingPropertiesPage.cs, XenModel/XenAPI-Extensions/Host.cs
This is allowed for both host and pool (on a host by host basis).
Signed-Off-By: Sharath Babu <sharath.babu@xitrix.com>
=> CP-17253: [XC] Ability to select VLAN PIF as a management interface of a host/Pool

XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.cs
XenCenter uses the wrong token (upload token instead of the diagnostic token) when the "Request an additional update" option is used
=> CA-243640: XenCenter HealthCheck Analysis Status Refresh is failing

XenAdmin/Core/Updates.cs, XenAdmin/Dialogs/OptionsPages/UpdatesOptionsPage.cs, XenAdmin/TabPages/ManageUpdatesPage.cs
XenCenter shows the wrong message on the Updates page when no updates are found
=> CA-244655 - XenCenter shows the wrong message on the Updates page

XenAdmin/Wizards/PatchingWizard/PatchingWizard_AutomatedUpdatesPage.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/PlanAction.cs, XenAdmin/Wizards/PatchingWizard/UpdateProgressBackgroundWorker.cs
This commit fixes a bug in the Update Wizard that causes XenCenter to not restart Toolstack when it should in the following case: in Automated Mode, when the update sequence for a host has an update --that contains live-patch with restartHost guidance (and guidance-mandatory=false)-- and which is followed by an update with Toolstack restart guidance.
=> CA-244687: Install Updates Wizard: Automated mode: bugfix for omitted after-apply-guidances

CFUValidator/CFUValidator.cs, CFUValidator/OutputDecorators/XenCenterUpdateDecorator.cs, XenAdmin/Core/Updates.cs, XenAdminTests/UnitTests/AlertTests/XenCenterUpdateAlertTests.cs, XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs, XenModel/Actions/Updates/XenCenterVersion.cs
- Add "latestcr" field to the XenCenterVersion class
- Change the Updates class to cope with multiple latest XenCenter versions
=> CP-21173: Show two latest XenCenter versions 

XenAdmin/Alerts/Types/XenCenterUpdateAlert.cs
- save multiple dismissed alerts as a comma-separated list in Settings.Default.LatestXenCenterSeen
=> CP-21174: Multiple dismissed XenCenterVersion alerts

XenAdmin/MainWindow.cs, XenModel/Actions/Action.cs, XenModel/Actions/PureAsyncAction.cs
Suppress updates to the status when the PureAsyncAction runs the action to populate the ApiMethodsToRoleCheck
=> CA-137249: Strange 'Completed' text shows while enabling or disabling HA

XenAdmin/Alerts/Types/XenServerPatchAlert.cs, XenAdmin/Alerts/Types/XenServerUpdateAlert.cs, XenAdmin/Alerts/Types/XenServerVersionAlert.cs, XenAdmin/Core/Updates.cs, XenAdmin/Diagnostics/Checks/XenCenterVersionCheck.cs, XenAdmin/Diagnostics/Problems/XenCenterVersionProblem.cs, XenAdmin/TabPages/ManageUpdatesPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- On the Updates tab: for new versions, check that the version of XenCenter is at least the latest. If not, give an additional option to download a newer XenCenter (for both updates and upgrades), and not offer "Download and Install" (for updates).
- In the Patching wizard: if the update is a new version, we force the user to first update their XenCenter to the new version
- In the RPU wizard: if the server version is not the latest and their XenCenter version is not the latest from updates.xml, we assume that they want to upgrade to the latest XenServer version and we force the user to first update their XenCenter to the latest version.
=> CP-21184: Add a check for the XenCenter version

XenAdmin/Alerts/NewVersionPriorityAlertComparer.cs, XenAdmin/TabPages/ManageUpdatesPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs, XenAdmin/XenAdmin.csproj
In the Updates wizard:
New versions that are available as updates will be listed in the "Download Updates from Citrix" section, before any other updates.
If XenCenter is not the latest version, these rows will be greyed out, with a tooltip.
=> CP-21500: Updates wizard: Show new versions that are available as updates

XenAdmin/Wizards/NewNetworkWizard.cs, XenModel/Actions/Network/CreateBondAction.cs
- set managed=true, otherwise the network creation fails with the error "The network is not managed by xapi"
=> CA-249824: Unable to create vlan, bond using XenCenter

XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
=> CA-248920: The radiobutton selection on Select Update page is not preserved while navigating to the previous page in the Install Update wizard

XenModel/Actions/PureAsyncAction.cs
CA-249624: [XSO-707] Convert VM to Template from XenCenter is not working if connected as an AD user
- Reset the action's Session after the PureAsyncAction is run to collect the RBAC method list.
Also fixes the bug where AD users cannot do multiple operations on the VMs [SCTX-2517]
=> CP-21782: Backport the fix for SCTX-2517 (CA-249624) to ely/bugfix

devtools/download_packages.ps1
Windows 7 (without sp1) comes with powershell v2.x and
download_packages.ps1 doesn't work with powershell v2.x.
Check for powershell version and bail out if Major version is less than
3.
Signed-off-by: Anoob Soman <anoob.soman@citrix.com>
=> download_packages: Check version of powershell before executing

XenAdminTests/HealthCheckTests/CredentialTests.cs, XenModel/Actions/HealthCheck/TransferHealthCheckSettingAction.cs, XenServerHealthCheck/ServerListHelper.cs
The problem with these tests was that XenServerHealthCheck/ServerListHelper class is reading the server list form the user config file, and it also saves it there on every update. Although this tests eventually remove the servers added, sometimes (e.g. the test fails midway through) the added server (e.g. "host1") remained in the config file. 
With this fix, we firstly clear the server list.
=> Fix the HealthCheck tests

XenAdminTests/HealthCheckTests/CredentialTests.cs, XenAdminTests/HealthCheckTests/RequestUploadTaskTests.cs
- Now that the credential receiver ignores empty credentials, this test needed to be updated to not send an empty password
- Moved initializing code in TestFixtureSetUp (and similarly tear-down code in TestFixtureTearDown) for both RequestUploadTaskTests and CredentialTests classes
- Also removed unnecessary calls to CreateNewConnection and LoadCache
=> CA-255458: Fix the HealthCheck tests - RequestUploadTaskTests

XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Network.cs
Network name will be shown as Network <NIC_ID> on VLAN <VLAN_ID>
Signed-off-by: Sharath Babu <Sharat.Babu@citrix.com>
=> CA-255015: Network Name for newly created vlan needs renaming from XenCenter

XenAdmin/Wizards/PatchingWizard/PatchingWizard_AutomatedUpdatesPage.cs
Due to a regression (introduced by [1]), XenCenter will not run delayed actions in the correct host-order at all times. This can cause the master to be not the first host to be rebooted what may result in connections being lost to slaves should the API change between restarts/updates in a way that it would not be compatible to the previous version. This would make the wizard fail and users would have to restart their master host manually to make it connect to its slaves again.
This commit fixes the order of the hosts when executing the delayed actions.
[1]: 15827512e1126e8a72d47aaa50ce7c8113262f5a
=> CA-255551: [SCTX-2553] Automated Updates - Slaves rebooted before Master - XenCenter 7.1.1

XenAdmin/TabPages/GeneralTabPage.cs
General tab (Pool): In the list of updates, added a space after each comma
to let the control wrap the text into multiple lines. This way the text is
no longer cut, therefore no additional scrollbar is needed.
=> CA-147943: Scrollbar for list of hotfixes installed in a pool doesn't have scrollbar the first time it is expanded

XenAdmin/MainWindow.cs, XenAdmin/Properties/Settings.Designer.cs, XenAdmin/Properties/Settings.settings, XenAdmin/app.config
=> CP-22471: Add information on XenCenter help usage to the user settings

XenAdmin/MainWindow.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardStoragePage.cs, XenAdmin/Wizards/NewSRWizard_Pages/SrWizardType.cs, XenModel/PoolJoinRules.cs, XenModel/Utils/Helpers.cs, XenModel/XenAPI-Extensions/Host.cs
Neither FalconOrGreater nor HonoluluOrGreater has been implemented in Honolulu. We can't implement the latter as the platform_version is not expected to change between Ely and Honolulu. To be able to backport the changes in CA-249084 (PR #1536), the consensus reached was to use ElyOrGreater instead. This way, from Ely, the PoolJoinRules will be less strict (fail later) and the build number will be hidden, although this seems to be the minimal impact and most straightforward solution. This PR implements these.
=> CP-22787: Backport CA-249084 from master

XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs, XenAdmin/Diagnostics/Problems/VMProblem/CannotMigrateVM.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Failure.cs
Detect both VM_LACKS_FEATURE and VM_LACKS_FEATURE_SUSPEND, show proper error message on the pre-check page in the Install Updates Wizard
=> CA-220047: Show proper precheck error when a VM cannot be migrated

XenAdmin/Commands/CrossPoolCopyVMCommand.cs, XenAdmin/Commands/CrossPoolMoveVMCommand.cs
(The member 'CanExecute()' does not hide an inherited member. The new keyword is not required)
=> CA-249858: Fix build warning as error

XenAdmin/SettingsPanels/VBDEditPage.Designer.cs, XenAdmin/SettingsPanels/VBDEditPage.cs, XenAdmin/SettingsPanels/VBDEditPage.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
This commit changes the dropdown control to not only show the available
positions, but also mark the ones that are already being used.
=> CA-224724: VBD edit page: show 'position in use' message on the dropdown items

XenModel/Messages.Designer.cs, XenModel/Messages.resx
Changed the text (on the checkbox) to make it clear that, after a version upgrade, XenCenter will apply updates only on licensed pools. This way it should be clear that servers of a partially licensed pool will not be updated. (The previous text suggested that any licensed server would be updated in general.)
=> CA-252924: Updates on new version are not applied for licensed host on Partially licensed pool

XenModel/XenAPI/FriendlyErrorNames.Designer.cs, XenModel/XenAPI/FriendlyErrorNames.ja.resx, XenModel/XenAPI/FriendlyErrorNames.resx, XenModel/XenAPI/FriendlyErrorNames.zh-CN.resx
This is another part of pull request on xapi-project/xen-api-sdk. 
https://github.com/xapi-project/xen-api-sdk/pull/107  => **[This pull request will be cancelled, as it is not needed to do there.]**
Both of them are for a new error message: POOL_AUTH_ENABLE_FAILED_INVALID_ACCOUNT
=> CA-254480: XenCenter error message refine for CA-205515

XenModel/PoolJoinRules.cs
- only check the updates on the master and the new slave
=> CA-259659: Revise the update homogeneity pool join rule

XenModel/PoolJoinRules.cs
* CA-259659: Revise the update homogeneity pool join rule
- only check the updates on the master and the new slave
* CA-259659: Revise the update homogeneity pool join rule
- simplify the algorithm that checks the updates on the master and the slave
=> CA-259659: Revise the update homogeneity pool join rule (#1692)

packages/DOTNET_BUILD_LOCATION
=> CA-260366: Updated dotnet build location reference to ctxsign

XenAdmin/SettingsPanels/Wlb/WlbAdvancedSettingsPage.cs
=> CA-260304: WLB Configuration parameters can not be reset in XenCenter 7.2

XenAdmin/Core/Updates.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/TabPages/ManageUpdatesPage.cs
1) Show required updates in case of versions without minimal patches
2) Hide version text in installed updates when version is Ely or above
=> CP-24210: Populate "By Host" view correctly

XenAdmin/TabPages/ManageUpdatesPage.cs
Keep order consistency with general tab for newer version servers.
=> CP-24210: fix the patch sorting in newer version

XenAdmin/TabPages/VMStoragePage.ja.resx
The bug is that two button texts are truncated in Japanese version. In
order to keep consistency, increase the width of all buttons to the same size.
=> CA-248292: Fix btn truncation in VM storage page

XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs
Fixed a bug that caused XenCenter to try to apply an update (that the user manually selected) multiple times and therefore failed. This was only present when the Select All button had been used.
=> CA-263044: [XSO-765] Install Update fails because it tries to install the hotfix to one pool twice

XenAdmin/TabPages/ManageUpdatesPage.cs
The bug is required updates for slaves of pre-dundee pool don't show.
=> CA-265410: Fix required updates for some hosts

XenAdmin/Controls/DataGridViewEx/PoolHostDataGridViewOneCheckboxRow.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardSelectPool.Designer.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardSelectPool.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardSelectPool.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Host.cs
Also includes some improvements to the Select Pools page of the RPU wizard
- do not show the checkbox if the item is disabled
- show the icon for the pool items, not only for hosts (making this consistent with the similar page in the Update Wizard)
=> CP-24498: RPU wizard to block the selection of unlicensed hosts

XenAdmin/Dialogs/AboutDialog.ja.resx, XenAdmin/Dialogs/AboutDialog.resx, XenAdmin/Dialogs/AboutDialog.zh-CN.resx, XenAdmin/Dialogs/DuplicateTemplateNameDialog.ja.resx, XenAdmin/Dialogs/DuplicateTemplateNameDialog.resx, XenAdmin/Dialogs/DuplicateTemplateNameDialog.zh-CN.resx, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.ja.resx, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.resx, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.zh-CN.resx, XenAdmin/Dialogs/LegalNoticesDialog.ja.resx, XenAdmin/Dialogs/LegalNoticesDialog.resx, XenAdmin/Dialogs/LegalNoticesDialog.zh-CN.resx, XenAdmin/Dialogs/WarningDialogs/VcpuWarningDialog.ja.resx, XenAdmin/Dialogs/WarningDialogs/VcpuWarningDialog.resx, XenAdmin/Dialogs/WarningDialogs/VcpuWarningDialog.zh-CN.resx, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.ja.resx, XenModel/FriendlyNames.resx, XenModel/FriendlyNames.zh-CN.resx, XenModel/Messages.Designer.cs, XenModel/Messages.ja.resx, XenModel/Messages.resx, XenModel/Messages.zh-CN.resx, XenModel/XenAPI/FriendlyErrorNames.ja.resx, XenModel/XenAPI/FriendlyErrorNames.resx, XenModel/XenAPI/FriendlyErrorNames.zh-CN.resx, devtools/spellcheck/spellcheck-brand-file.sh, mk/re-branding.sh
Following pattern would be caught when using "XenCenter" "XenServer" and
"Citrix":
1) not "[" or "/" or """ on left of the brand string
2) brand string followed by space followed by not "p", and optional letter
3) optional letter followed by space followed by the brand string
4) brand string followed by "," and optional letter
5) begin with the brand string
6) end with the brand string
tested with all .resx files
=> CP-266755 & CA-266843: Fix XC brand string

XenAdmin/Wizards/HAWizard_Pages/AssignPriorities.cs, XenAdmin/Wizards/HAWizard_Pages/AssignPriorities.resx
when the max tolerance is being calculated, the text and icon on top of HA
wizard is no longer visible after this fix.
=> CA-267671: Fix Configure HA wizard display text

XenAdmin/Wizards/PatchingWizard/PlanActions/BringBabiesBackAction.cs
Increased the wait between host_enable attempts, allowing to wait more for the host to reboot.
This will affect Automated Updates and other normal Patching Wizard
operations as well.
=> [SCTX-2608] Honolulu Update - Server is still booting error

XenAdmin/Controls/HaNtolControl.cs
This is caused by the `waitingNtolUpdate.waitOne()` call being at the end of the loop, not the beginning. The reason is that the `waitingNtolUpdate` is set during the first iteration (before the thread even gets loaded) - because the setter for Settings in this file sets it (and that's set by the setter for AssignPriorites.Connection, which is set in the HAWizard constructor). So when the thread first spawns we do the calculations, then get to the `waitOne` lock, which is set so we go back around the loop and calculate everything again before returning to the lock and waiting to be triggered. The correct behaviour is to trigger only once on the page load, and then only when re-triggered. To achieve that I've moved the `waitOne` call to the beginning of the loop, so that (assuming the …
=> [CP-24974] Avoid calculatingVM agility/failure tolerance twice

XenAdmin/Dialogs/AttachUsbDialog.cs, XenAdmin/SettingsPanels/USBEditPage.cs, XenAdmin/TabPages/UsbPage.cs, XenModel/Actions/USB/DeleteVUSBAction.cs, XenModel/XenAPI/FriendlyErrorNames.resx, XenModel/XenAPI/PUSB.cs, XenModel/XenAPI/Proxy.cs, XenModel/XenAPI/Relation.cs, XenModel/XenAPI/VUSB.cs
Change points from xapi:
1. Remove "attached" field in PUSB & VUSB.
2. Add "currently_attached" as a bool field in VUSB.
=> CP-25329: Refine API reference for PUSB & VUSB in xenadmin

XenAdmin/Dialogs/AttachUsbDialog.Designer.cs, XenAdmin/Dialogs/UsbUsageDialog.Designer.cs, XenAdmin/Help/HelpManager.ja.resx, XenAdmin/Help/HelpManager.resx, XenAdmin/Help/HelpManager.zh-CN.resx, XenAdmin/MainWindow.cs
This PR implements Context Help for USB-passthrough feature:
USBPage: HelpID = 1020. Show "Tabs" topics. Add "TabPageUSB" in HelpManager.resx.
USBEditPage: HelpID = 6241. Show "Change VM Properties" topic. No change in code.
UsbUsageDialog: Remove help button. 
AttachUsbDialog: Remove help button.
=> CA-270498: Link Help docs to new added USB-passthrough pages.

XenAdmin/MainWindow.cs
Fixed flickering that occurred due to the repetitive re-setting of the label's text.
=> CA-270499: The license text on the title bar is flickering

XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs
When we right click migrate a VM we load all the hosts in the pool into a dropdown, and then one-by-one assert whether the selected VM can boot on that host, enabling each option where this is positive. If the dropdown is exited then nothing stops these assert calls from continuing, and looking at the logs we can see that they do.
With a large pool this is problematic because the UI basically locks up until it's completed all these asserts, even if we've already selected a host to migrate to. If we try to migrate another host then we see in the logs that both the old thread and new thread are making `assert_can_boot_here` calls, and the UI for the new thread doesn't function until the old one has finished.
This commit adds a new property `_isDropDownClosed`, which is set by the new …
=> [CA-269110] Stop calling assert_can_boot_here after migrate dropdown is closed

XenAdmin/MainWindow.ja.resx, XenAdmin/MainWindow.zh-CN.resx
The problem was caused by out-of-update of layout in Chinese/Japanese resource.
In MainWindow, columns of layout tableLayoutPanel1 shoud be changed to 4 (from 2) to accommodate title label, license label and log-in label of selected object.
=> CA-272724: Missing user information in non-English XenCenter version.

XenAdmin/Diagnostics/Hotfixing/HotfixFactory.cs, XenAdminTests/UnitTests/Diagnostics/HotFixFactoryTests.cs
- RPU004 is applicable to Falcon as well as Ely hosts
=> CA-274150: Update RPU hotfixes in XenCenter

XenModel/XenAPI-Extensions/Host.cs
=> CA-273163: Fix the error where XenCenter did not set XenServer log destination and the iSCSI IQN settings

XenAdmin/Program.cs, XenModel/Network/IXenConnection.cs, XenModel/Network/XenConnection.cs
This PR is created to fix CA-272606.
When user close XenCenter main window, XenCenter go through all existing connections and log out the sessions. As the log-out operation involves server communication, XenCenter start a thread to do that for each session. These threads are assigned "Background" type and low priority. When all the foreground threads exit, all background thread will be killed. So race condition exist, if the foreground threads quit quickly, log-out operations haven't been done.
The solution is to set the logging-out thread as foreground in the case of exiting.
=> CA-272606: AD user can not log out when closing XenCenter.

XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard_SelectInstallMethod.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Changes brief:
- Once the "Test" button is clicked, the button text is changed to "Stop" instead of being disabled. 
- User can click "Stop" button again to cancel the test.
- The test is also canceled when user type "Previous" and "Cancel" button.
- As the text may change in run, so the text was moved into Messages resource file.
- The "cancel" function also applies for HTTP and FTP.
=> CA-272769: Enable user to cancel URL testing in rolling upgrade wizard.

XenAdmin/Diagnostics/Problems/VMProblem/AutoStartEnabled.cs
In RPU Precheck page, if user type Resolve or Resolve All to disable autostart-enabled VM, the refreshed listed can still contain autostart-enabled problem. Because the server update-and-notification took time, but the page was updated before server ready. 
Now a 1-second waiting is added before updating the Precheck page.
Note, in extreme situation, 1 second may not be enough to collect server response (for bad network, etc.). In that case, the fault can happen and user need to click "Check Again" or resolve again to update.
=> CA-271863: Can not automatically resolve autostart-enabled VM in RPU.

XenAdmin/SettingsPanels/ClusteringEditPage.cs, XenModel/Actions/Network/ChangeNetworkingAction.cs, XenModel/Actions/Network/NetworkingActionHelpers.cs
When configuring the IP address on the cluster network, we need to temporarily unplug all GFS2 SRs and disable clustering.
This commit also includes a fix to the action progress calculation.
=> CP-26131: IP Address Configuration when clustering is enabled

XenAdmin/Diagnostics/Checks/ServerSelectionCheck.cs, XenAdmin/Diagnostics/Problems/PoolProblem/ServerSelectionProblem.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- The new "server selection" precheck is added for Inverness or greater pools and checks if all the servers in the pool are selected (if update not already applied) when applying an update that has the "enforce-homogeneity" flag set to true
=> CA-276976: Add a new precheck in the Update Wizard

XenAdmin/Diagnostics/Checks/ServerSelectionCheck.cs, XenAdmin/Diagnostics/Problems/PoolProblem/ServerSelectionProblem.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- The new "server selection" precheck is added for Inverness or greater pools and checks if all the servers in the pool are selected (if update not already applied) when applying an update that has the "enforce-homogeneity" flag set to true
=> Cherry-picking to Jura: CA-276976: Add a new precheck in the Update Wizard

XenAdmin/Wizards/ImportWizard/GlobalSelectHost.cs, XenAdmin/Wizards/ImportWizard/ImportSelectHostPage.cs, XenAdmin/Wizards/ImportWizard/ImportWizard.cs, XenAdmin/Wizards/NewVMWizard/NewVMWizard.cs, XenAdmin/Wizards/XenWizardBase.cs
- Added a check so that we don't attempting to show the license warning if the wizard is open without a preselected host/pool.
- The license warning is now updated whenever the host selection changes; plus, we are not attempting to show it if the wizard is open without a preselected host/pool.
- Also a minor refactoring in the GlobalSelectHost page to fix this issue: when the wizard is open with a pre-selected host, we pass this to the page by assigning SelectedHost property, which in turn sets the m_selectedHost. The getter for SelectedHost  resets m_selectedHost to the selected item in the host list. If the getter is used before the host list selection is updated, then the desired pre-selection is lost, because m_selectedHost is reset to null.
Signed-off-by: Mihaela Stoica …
=> CA-280287: Fix the null reference exception on the Import wizard

xva_verify/verify_main.cs
Changes:
- Open input file in read mode to allow readonly data
- Allow reading from stdin with filename "-"
- test for compressed data, use decompression if needed.
Needed because we use compress=true in vm-export and have the images on a read-only share.
=> Some Enhancements to input stream handling in xva_verify

XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateStoragePage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrationStorageResource.cs, XenAdmin/Wizards/GenericPages/SelectVMStorageWithMultipleVirtualDisksPage.cs, XenAdmin/Wizards/GenericPages/StorageResource.cs, XenAdmin/Wizards/ImportWizard/OVFStorageResource.cs
Solution brief:
1. Add abstract method IsExtraSpaceNeeded() in SelectVMStorageWithMultipleVirtualDisksPage to calculate whether extra space is needed in the operation. No extra space is required if source and target SR is the same one and the operation is migrating or moving, not required otherwise.
2. In making each combobox item. Legacy behavior was to check if there is enough space on target SR to accommodate source disk(s). Now "is-extra-space-needed" condition is also taken into account.
Note:
1. SelectVMStorageWithMultipleVirtualDisksPage is common used for migrate/copy/move/import wizard.
2. There is interface update.
Signed-off-by: Michael Zhao <michael.zhao@citrix.com>
=> CA-280322: Space requirement calculation error in migration wizard.

XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_AutomatedUpdatesPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/DownloadPatchPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/UploadPatchToMasterPlanAction.cs
When applying a "new version" update, XenCenter starts an automated updates sequence that by default downloads all the updates. However, when using an update from disk, we shouldn't download it again.
With these changes, when an update from disk is used we save the [update, path] mapping, which we then use in the automated updates sequence, so we don't download that update again.
Also fixed a bug where a zipped update file from disk is not identified as a new version.
=> CA-281646: Do not download the update again when using an update from disk

XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateDestinationPage.cs, XenAdmin/Wizards/GenericPages/SelectMultipleVMDestinationPage.cs, XenAdmin/Wizards/ImportWizard/ImportSelectHostPage.cs
Major modifications:
1. Create new overload of function `CreateTargetServerFilterList` in `SelectMultipleVMDestinationPage.cs` with one more argument, type `List<VM>` ;
2. Rewrite new overload function `CreateTargetServerFilterList` in sub-class `CrossPoolMigrateDestinationPage` ;
3. Call `CreateTargetServerFilterList ` with each `VM` later in function `PopulateDataGridView` ;
=> CA-280329: Fix CrossPoolMigrateDestinationPage with Current Server showing

XenAdmin/Actions/GUIActions/ExternalPluginAction.cs, XenAdmin/ConsoleView/XSVNCScreen.cs, XenAdmin/Controls/CustomDataGraph/ArchiveMaintainer.cs, XenAdmin/Diagnostics/Checks/DR/AssertCanBeRecoveredCheck.cs, XenAdmin/Dialogs/EvacuateHostDialog.cs, XenAdmin/Plugins/Features/TabPageFeature.cs, XenAdmin/Plugins/Placeholders.cs, XenAdmin/WinformsXenAdminConfigProvider.cs, XenModel/Actions/AsyncAction.cs, XenModel/Actions/CancellingAction.cs, XenModel/Actions/DR/DrRecoverAction.cs, XenModel/Actions/Host/HostBackupRestoreAction.cs, XenModel/Actions/Host/SingleHostStatusAction.cs, XenModel/Actions/Pool_Patch/ApplyPatchAction.cs, XenModel/Actions/Pool_Patch/UploadPatchAction.cs, XenModel/Actions/SupplementalPack/UploadSupplementalPackAction.cs, XenModel/Actions/VM/ExportVmAction.cs, XenModel/Actions/VM/ImportVmAction.cs, XenModel/Network/XenConnection.cs, XenModel/WLB/WlbReportAction.cs, XenModel/XenAPI-Extensions/Blob.cs, XenModel/XenAPI-Extensions/Session.cs, XenModel/XenAPI-Extensions/Task.cs, XenModel/XenAPI-Extensions/VM.cs, XenModel/XenAPI-Extensions/VM_appliance.cs, XenModel/XenSearch/MetricUpdater.cs, XenOvfTransport/Import.cs, XenOvfTransport/iSCSI.cs, XenServerHealthCheck/XenServerHealthCheckConfigProvider.cs
Use the opaque_ref so it's obvious what it is. The Session's uuid will be deprecated from the API bindings.
Note that I haven't included the changed bindings in this PR, it can be done next time we update them from the SDK in master.
=> CA-40854: The Session's uuid is in reality its opaque_ref.

XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateDestinationPage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs, XenAdmin/Wizards/GenericPages/DelayLoadingOptionComboBoxItem.cs, XenAdmin/Wizards/GenericPages/ReasoningFilter.cs, XenAdmin/Wizards/GenericPages/SelectMultipleVMDestinationPage.cs
Solution brief:
1. Add a cache for CrossPoolMigrateCanMigrateFilter to save the result of server call VM.assert_can_migrate().
2. Add cancel method to filter.
3. Don't change the update of server list combo-box from sync to async. No server call would be made in building the server list due to the introduction of cache.
4. Sort server list.
The solution was a little bit different (point 3 mentioned above) from the one described in CA-272150 solution slides on which we have discussed.
=> CA-272150: Optimize destination page of cross-pool-migrate wizard.

XenAdmin/Dialogs/NetworkingPropertiesPage.cs, XenModel/XenAPI-Extensions/Network.cs
As the requirement requested, the Mangement Interface shouldn't use the SR-IOV network because the Dom0 shouldn't use the VF(virtual function).
=> CP-27188: Filter out the SR-IOV network when configuring IP address

XenModel/XenAPI/Converters.cs
The SDK counterpart: https://github.com/xapi-project/xen-api-sdk/pull/143
=> Return null if the string to deserialize to a XenRef<T> or DateTime is null

XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs, XenAdmin/Commands/Controls/VMOperationToolStripMenuSubItem.cs, XenAdmin/Controls/VisualMenuItem.cs, XenModel/Actions/ProduceConsumerQueue.cs
This PR covers 3 CA's exactly: CA-284226, CA-277201 and CA-273151. It improves the performance of the menus by:
1. Reduce the count of API calls (triggered by CanExecute()) for updating each menu item by 1.
2. Make API calls for each menu item concurrent.
3. Optimize the algorithm in updating menu UI.
=> CA-284226: Optimize performance of menu Start-on-Server and Migrate-to-Server

XenAdmin/Core/Updates.cs, XenAdminTests/UnitTests/AlertTests/XenServerUpdateAlertTests.cs, XenAdminTests/UnitTests/BatchUpdatesTests/BatchUpdatesTests.cs, XenModel/Actions/Updates/DownloadUpdatesXmlAction.cs, XenModel/Actions/Updates/XenServerVersion.cs
Using minimum_xc_version attribute in xenserver version to
determine which xencenter version is required.
=> CA-286458: Fix latestcr XC requirement when apply CR update

XenServerHealthCheck/RequestUploadTask.cs
**Root cause:**
The logic here was: when a failed upload happened before a successful upload, scheduled upload would never happen again.
**Solution:**
We only take lastSuccessfulUpload into account when we are considering whether we need a retry after a previous failure:
- If no successful upload exists or the last successful upload is to early, we need to retry.
- If a successful upload existed and it happened after last failure, we don't retry.
Signed-off-by: Michael Zhao <michael.zhao@citrix.com>
=> CA-284135: Issues with scheduled uploads in the Health Check service.

XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs
The PR aims to fix the crash when a user pops up Migrate-to-Server menu repeatedly and quickly. The problem is more probable to happen if the server list is long.
The root cause is two or more threads can be created to update the menu in parallel, if the user operates quickly enough, which definitely lead to a program crash.
The solution is to guarantee only one thread is working on menu update. If the previous menu has been closed and a new menu is to be made, we need to make sure the previous job quit safely (don't invoke main window any more) before starting a new job.
=> CA-286291: Fix the crash when quickly and repeatedly popping up Migrate-to-Server menu

XenAdmin/Dialogs/LicenseManager/LicenseStatus.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenModel/Utils/AsyncServerTime.cs
Also, no need to trigger an event when the host is null or when get_servertime
fails only to double-log it in the handling class.
=> CA-289153: Do not attempt updating the licence status for disconnected hosts.

XenAdmin/Commands/Controls/VMOperationToolStripMenuItem.cs, XenAdmin/Commands/Controls/VMOperationToolStripMenuSubItem.cs, XenAdmin/Commands/Controls/WlbRecommendations.cs, XenModel/Actions/WLB/WlbRetrieveVmRecommendationsAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenModel.csproj
- added an action for the API call that retrieves the WLB VM recommendations
- removed the thread used for updating the menu items, so that we always access the menu items on the UI thread and do only the server calls on separate threads (for WLB, getting the recommendations now is done on the new action, for non-WLB we have the `workerQueueWithoutWlb`)
=> CA-286291: Refactoring in VMOperationToolStripManuItem

XenModel/XenSearch/GroupAlg.cs, XenModel/XenSearch/Sort.cs
I believe the inconsistency here was that, when comparing a XenObject with a non-XenObject, there were two code paths with same circumstances but different results. For example, if _1 were a nonXenObject and _2 a XenObject, then line 177 in GroupAlg.cs would return -1, but line 186 would call Sort and line 150 in Sort.cs would return 1 (which was also wrong since non-XenObject come before XenObjects; this bit did not take account of ascending/descending order either). Other problems include calling GetType() and ToString() on null if all _1, _2 and search were null.
=> CA-289182: Corrections to sorting (clearer handling of null cases, non-XenObjects, logic path inconsistencies).

XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/HostPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/RestartHostPlanAction.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs
- In the RPU case, re-enable the host after the upgrade is done, as the host will be put back into maintenance mode when needed during the update process.
- The VMs should not be repatriated during the RPU
- When a host is rebooted, it needs to be disabled first (even if an evacuation is not needed), otherwise the reboot won't happen
=> CP-28279: Corrections to the plan actions

XenAdmin/Dialogs/ThreeButtonDialog.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/DownloadPatchPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/PlanAction.cs, XenAdmin/Wizards/RollingUpgradeWizard/PlanActions/UpgradeManualHostPlanAction.cs, XenAdminTests/WizardTests/RollingUpgradeWizardTest.cs
The reason why the confirmation dialog is launched in this case is that the DownloadPatchPlanAction starts a download action which is shown in the Action history. d3f761b070c5ac27091e83b33028a31a1f8b6b5a has corrected the behaviour in that we see a cancellation and not a failure error. Additionally, the download action should not be shown in history. This is fixed by this PR. Beyond this, the confirmation dialog should be checking whether there are _PlanActions_ active, to prevent the user from accidentally closing XenCenter thus interrupting their update. However, this is an improvement for master that goes beyond the current scope.
=> CA-292363: Do not show the DownloadAndUnzipXenServerPatchAction in action history.

XenAdmin/Diagnostics/Checks/PBDsPluggedCheck.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/HostPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/RebootPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/RebootVMsPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/VMsPlanAction.cs, XenModel/Network/XenConnection.cs, XenModel/XenAPI-Extensions/PBD.cs
...do not log a message in this case as the SRs are reconnected after reboot and this may lead
to duplicate messages. Also, simplified check-and-plug methods for PBDs to avoid
repetition of iterations.
=> Check and plug PBDs for VMs only if and when there are VMs to migrate;

XenAdmin/TabPages/SnapshotsPage.cs
Till XenCenter Version 7.4 (my feeling, can be wrong) the default view on the snapshot page was Treeview.
With commit https://github.com/xenserver/xenadmin/pull/1767/commits/4825b60a60d74c2d7b32f3291747b78dc09e4d72#r200793051 the behaviour changed to Listview as default, maybe without intention :-)
The if-statement `if (_storedViewsPerVm.ContainsKey(m_VM.opaque_ref) && _storedViewsPerVm[m_VM.opaque_ref] != SnapshotsView.ListView)` is always false if I open the snapshot page the first time after start of XenCenter, so it jumps always to the else-branch which opens the Listview/Gridview.
I changed it, so that Treeview is the default again (https://github.com/xcp-ng/xenadmin/issues/62)
=> Snapshot view: Treeview as default (like in the past)

XenAdmin/Core/Updates.cs, XenAdmin/Diagnostics/Checks/AutomatedUpdatesLicenseCheck.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard_UpgradeMode.cs
... because pre-Dundee hosts dont't have this license flag, but they might have it after the upgrade.
Also added a bit more logging in the function that generates the update plan actions
=>  CA-293682: In the RPU wizard, only check the batch hotfix license restriction for Dundee or greater hosts

XenAdmin/SettingsPanels/ClusteringEditPage.Designer.cs, XenAdmin/SettingsPanels/ClusteringEditPage.cs, XenAdmin/SettingsPanels/ClusteringEditPage.resx
1) When create/delete bond, inconsistent cluster network may occur. Show
warning in this case.
2) Refactor UI on cluster network edit page.
=> CA-292377: Show warning if no cluster network found

XenAdmin/IMainWindow.cs, XenAdmin/MainWindow.cs, XenAdmin/TabPages/ManageUpdatesPage.cs, XenAdmin/Wizards/XenWizardBase.cs, XenAdminTests/MainWindowWrapper/MockMainWindow.cs
I couldn't find way to go to second page of the Update wizard, when using .showForm() method. But I don't think it's a necessary functionality. Also, IMO, we don't need to pre-select any server in this case. So it does exactly the same thing as clicking from the main menu.
=> CA-294091: Fix two Update wizards co-exist bug

XenAdmin/Commands/ForceVMRebootCommand.cs, XenAdmin/Commands/ForceVMShutDownCommand.cs, XenAdmin/Commands/RebootVMCommand.cs, XenAdmin/Commands/ResumeVMCommand.cs, XenAdmin/Commands/ShutDownVMCommand.cs, XenAdmin/Commands/StartVMCommand.cs, XenAdmin/Commands/SuspendVMCommand.cs, XenAdmin/Commands/VMOperationCommand.cs, XenAdmin/MainWindow.cs, XenAdmin/TabPages/AlertSummaryPage.Designer.cs, XenAdmin/TabPages/AlertSummaryPage.cs, XenAdmin/TabPages/HistoryPage.Designer.cs, XenAdmin/TabPages/HistoryPage.cs, XenAdmin/TabPages/ManageUpdatesPage.Designer.cs, XenAdmin/TabPages/ManageUpdatesPage.cs, XenAdmin/TabPages/NotificationsBasePage.cs, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Created a new base class for the Notifications pages (Alerts, Updates, Events). This can be used in the future to host more of the common code between these pages. For now, it implements a common mechanism for showing/hiding the page and ensures that the event handlers are deregistered when the page is hidden (i.e. when the user switches to a different view) and registered again when the page becomes visible
=> CA-286882: Shutting down large number of VMs causes XenCenter to hang

XenAdmin/Dialogs/AssignLicenseDialog.cs, XenAdmin/Dialogs/AssignLicenseDialog.resx, XenModel/Actions/Host/ApplyLicenseEditionAction.cs, XenModel/Actions/Host/LicensingHelper.cs, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/Utils/Helpers.cs, XenModel/XenAPI-Extensions/Host.cs
Modify the names in AssignLicenseDialog, FriendlyNames.resx and Messages.resx.
Note, FriendlyNames.Designer.cs and Messages.Designer.cs also include some modification from "[XenServer]" to "server". They were introduced in a preceding commit, but I forgot to commit the *.Designer.cs files.
=> CP-29230: Change License names (Enterprise to Premium, Free to Express)

XenModel/XenAPI/ApiVersion.cs
=> CP-29440: Prevent connections to XenServer >= 7.2 in Havana.

XenAdmin/MainWindow.cs, XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/PatchPrecheckOnHostPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/RestartHostPlanAction.cs, XenAdmin/Wizards/PatchingWizard/PlanActions/UploadPatchToMasterPlanAction.cs, XenAdmin/Wizards/WizardHelpers.cs, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.resx
With this change, following are working:
1) After applying XS75E003-5 only restart host, no restart toolstack
2) After applying vGPU driver on 7.4, restart host happens
=> CA-298913 + CA-297215: Fix restartHost and restartXapi bugs after patching

XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Host.cs
This PR contains:
1. Remove branding from Build data, Build number and Version in general tab page.
2. Show different branding in Name field of general tab page according to server version. 
=> CA-298954: Match server branding and version.

XenAdmin/Wizards/ExportWizard/ExportFinishPage.Designer.cs, XenAdmin/Wizards/ExportWizard/ExportFinishPage.cs, XenAdmin/Wizards/ExportWizard/ExportFinishPage.resx
Set verify on export default to false, added a warning when checkbox is checked (true).
Visual Studio seems to have made some minor changes to files automatically, as I'm new I have no idea if this is an issue or not but I've tested the changes work and I can verify that they do.
CP-Ticket: https://issues.citrite.net/browse/CP-29106
=> Disable automatic VDI Integrity check on export and scare the user if turned on

XenAdmin/TabPages/AdPage.cs, XenAdmin/TabPages/HistoryPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
For this purpose, call the DisconnectCommand instead of session.logout_subject_identifier.
Also:
- Add the new actions to the History synchronously on the main thread,
otherwise the warning dialog may not detect in time the new actions.
- Although the local root account is currently first in the list, checking whether
the first item is selected is a fragile way of establishing whether the local
root account is selected. Check the row's IsLocalRootRow property as in the
rest of the file.
- Added username detail to the logout action; fixed typo in message key.
- Some minor refactoring to make the code more efficient.
=> CA-237915: When one attempts logging oneself out, warn them if there are outstanding actions.

XenAdmin/Program.cs
Avoid calling ProfessionalColors before we have called Application.EnableVisualStyles as it causes visual styles to be prevented from being enabled and can prevent the program from displayed as expected as the value of Application.InitializeComCtlSupportsVisualStyles is found only one time when first needed and cached. If Application.useVisualStyles is not true as in this case it relies on calling "comctl32.dll" methods to determine if this is the case and after KB4462933 this is no longer the case.
=> CA-301193: XenCenter UI looks ugly after installation of latest Win10 CU update

XenModel/Actions/HealthCheck/UploadServerStatusReportAction.cs, XenModel/Actions/HealthCheck/XenServerHealthCheckUpload.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenServerHealthCheck/XenServerHealthCheckBundleUpload.cs
Also, call the XenServerHealthCheckUpload in a using block; use the FileInfo.Open
method to open the zip file for upload.
=> CA-301501: Update the progress bar for the action uploading a server status report.

XenAdmin/Commands/NewFolderCommand.cs, XenAdmin/Commands/NewTemplateFromSnapshotCommand.cs, XenAdmin/Controls/Folders/FolderEditor.cs, XenAdmin/Controls/Folders/FolderListItem.cs, XenAdmin/Controls/TreeViews/FolderChangeDialogTreeView.cs, XenAdmin/Controls/TreeViews/MultiSelectTreeView.cs, XenAdmin/Dialogs/FolderChangeDialog.Designer.cs, XenAdmin/Dialogs/FolderChangeDialog.cs, XenAdmin/Dialogs/FolderChangeDialog.resx, XenAdmin/Dialogs/InputPromptDialog.Designer.cs, XenAdmin/Dialogs/InputPromptDialog.cs, XenAdmin/Dialogs/InputPromptDialog.resx, XenAdmin/XenAdmin.csproj, XenAdminTests/DialogTests/DialogsWithDefaultConstructor.cs, XenAdminTests/DialogTests/OtherDialogs.cs, XenAdminTests/MainWindowWrapper/InputPromptDialogWrapper.cs, XenModel/Actions/Folders/FolderAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- Corrected folder selection; reduced clicks required to select folders;
improved text; added delete button.
- Moved FolderChangeDialogTreeView to the same folder as the other TreeViews;
- Added missing null checks to the MutliSelectTreeView and hid properties
HScrollPos and VScrollPos from VS's designer (the former was initialised
to zero every time the designer was updated, causing the treeview images
to disappear).
=> CA-302791: Rewrote the ChangeFolder dialog to fix usability issues.

XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx
If, for example, the host was disconnected, poolUpdateFromHost was null,
which was causing a silent exception resulting to an empty precheck list
shown on the page.
=> CA-303201: Added null check for the update on host corresponding to the selected update.

XenAdmin/Help/HelpManager.cs, XenAdmin/MainWindow.cs, XenAdminTests/UnitTests/HelpManagerTests.cs, XenAdminTests/XenAdminTests.csproj, XenModel/InvisibleMessages.Designer.cs, XenModel/InvisibleMessages.resx
Signed-off-by: Aaron Robson <aaron.robson@citrix.com> (+2 squashed commit)
Squashed commit:
[0350c0a6] CP-29875: Include campaign, medium and source in the help URLs.
[1e1c1c1c] CP-29875: Refactor and unit test current help URL behavior.
=> CP-29875: The docs.citrix.com links from XenCenter should include tags that give information about the source of the request

Branding/branding.sh, WixInstaller/XenCenter.wxs, XenAdmin/Diagnostics/Hotfixing/HotfixFactory.cs, XenAdminTests/UnitTests/Diagnostics/HotFixFactoryTests.cs
- Removed RPU001 and RPU002, as 6.x versions are not supported in XenCenter anymore
- Replaced RPU003 and RPU004 with new versions
- Added RPU005 for Lima
=> CP-30597: Update the RPU hotfixes

XenAdmin/Wizards/BootModesControl.cs, XenAdmin/Wizards/ImportWizard/ImportBootOptionPage.resx, XenAdmin/Wizards/ImportWizard/ImportWizard.cs, XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
-  hide the boot mode control if there is only one option (BIOS boot);
- add text "(experimental)" to the experimental options (in the radio button text);
- if an option is disabled, then hide the experimantal warning, as there is already a note saying why it is disabled;
- more detailed experimental warning.
=> CA-310250: Improvements to the guest UEFI UI

XenAdmin/Actions/GUIActions/MeddlingAction.cs, XenAdmin/Actions/GUIActions/MeddlingActionTaskSpecifications.cs, XenModel/Actions/VM/VMRebootAction.cs, XenModel/Actions/VM/VMShutdownAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/Task.cs
- Refactored MeddlingAction and Task classes: moved the logic for building a MeddlingAction outside the Task class and switched to using the vm_operations enum to identify which tasks are suitable for MeddlingAction
=> CA-309844: Fix meddling actions

XenAdmin/SettingsPanels/LogDestinationEditPage.Designer.cs, XenAdmin/SettingsPanels/LogDestinationEditPage.cs, XenAdmin/SettingsPanels/LogDestinationEditPage.resx, XenAdmin/TabPages/GeneralTabPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
The radiobuttons local-remote gave the impression the two types of logging
were mutually exclusive. Use a checkbox instead to make it obvious that
the logs are directed to a remote server in addition to being stored locally.
=> CA-309152: Remote logging is offered in addition to local and not instead of it

CommandLib/CommandLib.csproj, CommandLib/XXHash.cs, CommandLib/export.cs, XenAdmin/Dialogs/LegalNoticesDialog.resx
Xapi is moving from SHA1 to xxHash for VM imports and exports. These changes allow XenCenter to verify this new format whilst also maintaining backwards compatability. The xxHash code comes from [here ](https://github.com/differentrain/YYProject.XXHash) and is under an MIT license. 
I have manually tested these changes by running all combinations of imports and exports across new and old versions of Xapi.
=> CP-29310 & CP-30765: added support for the new xxHash-based VM imports and exports

XenAdmin/Controls/PDSection.Designer.cs, XenAdmin/Controls/PDSection.cs, XenAdmin/Controls/PDSection.resx, XenAdmin/TabPages/GeneralTabPage.Designer.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/TabPages/GeneralTabPage.resx
- CA-164372: Added line breaks in the pool updates list for readability and to match the corresponding host list.
- Moved the updates, version and licence sections closer together.
- Removed unnecessary panels and placed top buttons on a TableLayoutPanel.
- Moved size hardcoded values from the code to the resource files.
=> General TabPage layout modifications (includes CA-164372).

XenModel/Actions/VM/CreateVMAction.cs, XenModel/Actions/VM/GpuAssignAction.cs
Fix mistake when creating a VM with vGPUs from a template:
1. Reset opaque_ref before starting GpuAssignAction to trigger recreating of all vGPUs.
2. In GpuAssignAction, specify Gpu.device to keep the value from template.
=> CA-320459: Mistake in handling vGPUs when creating a VM from template.

XenAdmin/SettingsPanels/GpuEditPage.cs, XenModel/Actions/VM/GpuAssignAction.cs, XenModel/XenAPI/VGPU.cs
Signed-off-by: Lin Liu <lin.liu@citrix.com>
This commit change the valid `device` id range for a  VM from `[11,31]` to `[0,20]` for the backward compatibility
=> CA-322735: Keep XenCenter showing the real device number used in the VM

mk/re-branding.sh
This should fix the broken build.
=> CP-14806: Removed outdated databases from the rebranding.

Jenkinsfile
Also, removed echoing the test start and finish time as it is included
in the nunit3-console output.
=> CP-30453: Corrected the check for nunit test failures.

XenAdmin/Commands/HACommand.cs, XenAdmin/Dialogs/EditVmHaPrioritiesDialog.cs, XenAdmin/TabPages/HAPage.cs, XenAdmin/Wizards/HAWizard_Pages/AssignPriorities.cs, XenModel/Actions/Pool/EnableHAAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
When the statefile is missing (or when there are multiple statefiles, but I can't find any justification for this restriction), the code returns half way through the EditVmHaPrioritiesDialog's constructor, and Dispose is called. The latter tries to deregister events on AssignPriorities, however crashes because there is no connection. Adding a null check fixes the crash, however afterwards the code returns silently leaving the user wondering why nothing happened when the button was clicked. The behaviour is improved by adding relevant error pop-ups. Did some refactoring too to avoid code duplication.
=> CA-280117 + Crash on HA configure corner case

XenAdmin/Dialogs/ConversionDialog.cs, XenModel/Actions/XCM/ActivateConversionVpxAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenModel.csproj
This moves the functionality of the conversion-plugin in XenCenter, and adds two enhancements: (1) allows starting the VPX from states other than halted and (2) allows obtaining an IP address if the VPX external network is on vif.device!=1 (because I noticed that on some occasions no IP was obtained even if the VPX had started).
=> Activate the conversion VPX and get the service IP address without employing the conversion plug-in.

XenAdmin/Dialogs/ScheduledSnapshots/ScheduledSnapshotsDialog.resx, XenAdmin/Wizards/NewPolicyWizard/NewPolicySnapshotTypePage.Designer.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Also, use an info (instead of warning) icon on the message for Disk and memory snapshot
=> Fix menu and dialog title inconsistencies for Snapshot schedules.

XenAdmin/Commands/Controls/AssignVMGroupToolStripMenuItem.cs, XenAdmin/Dialogs/VmSnapshotDialog.Designer.cs, XenAdmin/Dialogs/VmSnapshotDialog.cs, XenAdmin/Dialogs/VmSnapshotDialog.resx
- make the info messages icon+text instead of clickable icons. Some rearrangements of the controls on the dialog to accommodate them.
- in the "Assign To Snapshot Schedule" dropdown item, do not add a separator if there are no suitable policies listed.
=> CP-32070: Fix icon visibility + some improvements

XenAdmin/Wizards/BugToolWizardFiles/BugToolPageDestination.cs, XenAdmin/Wizards/BugToolWizardFiles/BugToolWizard.cs, XenAdmin/Wizards/ExportWizard/ExportAppliancePage.cs, XenAdmin/Wizards/ImportWizard/ImportSourcePage.cs, XenCenterLib/Win32.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- Moved path validation checks from the wizard to its last page (planning
to remove XenWizardBase.FinishCancelled in future).
- If the directory did not exist, the user saw a message about inability
to write a file which was misleading. Check directory existence explicitly.
- Populate the last wizard page on load rather than on construction to
avoid unnecessary validations.
- Save in the settings the report output directory, not the filename.
=> CA-325439 Pre-populate download locations. Validation corrections on  the server status report wizard.

XenAdmin/Diagnostics/Checks/PVGuestsCheck.cs, XenAdmin/Diagnostics/Problems/PoolProblem/PoolHasPVGuestWarningUrl.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs, XenAdmin/XenAdmin.csproj, XenModel/InvisibleMessages.Designer.cs, XenModel/InvisibleMessages.ja.resx, XenModel/InvisibleMessages.resx, XenModel/InvisibleMessages.zh-CN.resx, XenModel/Messages.Designer.cs, XenModel/Messages.ja.resx, XenModel/Messages.resx, XenModel/Messages.zh-CN.resx, XenModel/Utils/Helpers.cs, XenModel/XenAPI-Extensions/VM.cs
Signed-off-by: Xueqing Zhang <Xueqing.Zhang@citrix.com>
Add the PV guests precheck in both 'Install update' and 'RPU'. This precheck will give a warning when host have pv guess. 
The warning link is not ready yet , a likely link given for example.
The PV guests want to skip this check can add one key in vm.other_config named "pvcheckpass".
=> CP-32033 Add PV guests precheck in Xencenter

XenCenterVNC/MyStream.cs
=> CA-328060: Set a limit of 1 MB to the VNC clipboard buffer

XenAdmin/Controls/SrPicker.cs, XenAdmin/Controls/SrPickerItem.cs
- Compacted code deciding whether to show an SR on the picker.
- Removed code sorting the disabled SRs because it repeats partially the SR checks without reflecting exactly the disabled reason and probably causes confusion when compared with the main treeview.
- Renamed property.
=> CA-329317: When migrating a VDI do not enable target SRs that do not allow mirroring

XenCenterLib/StreamUtilities.cs, XenOvfTransport/iSCSI.cs
Do not leave out bytes if the number read is odd, which can happen if the file is smaller than the buffer used.
=> CA-329687: Fixed verification code error.

XenAdmin/Controls/SrPickerItem.cs, XenAdmin/Wizards/ConversionWizard/SrSelectionPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.ja.resx, XenModel/Messages.resx, XenModel/Messages.zh-CN.resx
Signed-off-by: Xueqing Zhang <xueqing.zhang@citrix.com>
Add two kinds of warning in SR select wizard in Conversion Manager. One for the limit in Xapi that 'MAX_VHD_SIZE = 2040 * 1024 * 1024 * 1024' in sm/drivers/vhdutil.py , another for supporting to select a gfs2 SR smaller than request.
=> CA-330890: update storage select wizard in XCM

XenAdminTests/LicensingTests/ProductColumnComparerTests.cs
It seems Mock doesn't like very much optional parameters in the constructor.
=> CA-331420: fixed broken tests.

XenAdmin/Alerts/Types/HotfixEligibilityAlert.cs, XenModel/Alerts/Types/Alert.cs
The Title and Description of HotfixEligibilityAlert  involve calculation of local
time which should be done on the UI thread, otherwise the time is not localised
correctly, and additionally the application crashes when dismissing or sorting
these alerts.
Also, stop spamming the logs with each alert removal; code efficiency correction.
=> CA-333236:  Calculate local time for HotfixEligibilityAlert properties on the UI thread.

XenAdmin/Actions/GUIActions/Wlb/WlbOptimizePoolAction.cs, XenAdmin/Commands/AddVirtualDiskCommand.cs, XenAdmin/Commands/AttachVirtualDiskCommand.cs, XenAdmin/Commands/ConvertVMToTemplateCommand.cs, XenAdmin/Commands/CopyTemplateCommand.cs, XenAdmin/Commands/CopyVMCommand.cs, XenAdmin/Commands/HostMaintenanceModeCommand.cs, XenAdmin/Commands/InstallToolsCommand.cs, XenAdmin/Commands/MoveVMCommand.cs, XenAdmin/Commands/VMOperationCommand.cs, XenAdmin/Controls/XenSearch/QueryPanel.cs, XenAdmin/Core/History.cs, XenAdmin/Dialogs/WarningDialogs/VcpuWarningDialog.cs, XenAdmin/Dialogs/XenDialogBase.cs, XenAdmin/IMainWindow.cs, XenAdmin/MainWindow.cs, XenAdmin/XenSearch/Columns.cs, XenAdminTests/MainWindowWrapper/MockMainWindow.cs
- CA-335633: Prevent crash due to iterating through modified dictionary. Ensure that per-XenObject dialogs closed by the user are removed from the tracking table.
- Removed duplicate method.
=> CA-335633: crash and leaking forms

CommandLib/thinCLIProtocol.cs, xe/Xe.cs
Signed-off-by: minli1 <min.li1@citrix.com>
=> CP-33433: Limit XE client to PUT the same file with initial XE commands.

XenAdmin/Properties/AssemblyInfo.cs, XenAdminTests/CodeTests/AssemblyTests.cs, XenAdminTests/Properties/AssemblyInfo.cs, XenCenterLib/Archive/TarArchiveIterator.cs, XenCenterLib/Archive/TarArchiveWriter.cs, XenCenterLib/Archive/ZipArchiveIterator.cs, XenCenterLib/Archive/ZipArchiveWriter.cs
- Exclude VNC key map from l10n tests.
- Added parameterless constructors to the archive classes for use by the tests.
- Scalability tests were removed.
=> Test corrections. Fixes build failure.

XenAdmin/ConsoleView/VNCView.Designer.cs, XenAdmin/ConsoleView/VNCView.cs
Disposing the vncTabView disconnects the RdpClient and should not be called after
base.Dispose() is called on VNCView, because the latter has released the COM objects
and causes an InvalidComObjectException to be thrown.
=> CA-339374: Changed order of control disposal. Also, fixed wrong title of the undocked console.

XenAdmin/Dialogs/HealthCheck/HealthCheckOverviewDialog.cs, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.Designer.cs, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.cs, XenAdmin/Dialogs/HealthCheck/HealthCheckSettingsDialog.resx, XenAdmin/MainWindow.cs, XenModel/Actions/HealthCheck/GetHealthCheckAnalysisResultAction.cs, XenModel/HealthCheckSettings.cs
- Typo.
- Added controls to display the error in case authentication fails.
- Use the same control (LinkLabel) to show the rubric either when new authentication is needed or an existing one can be used.
- Moved privacy policy statement next to the checkbox because it looked crammed.
Commits best reviewed separately. It's also recommended to check out the code and quickly run it due to the inherent difficulty of diffing designer changes.
=> CA-337270: Perform authentication on a background thread.

XenAdmin/Alerts/Types/MessageAlert.cs, XenModel/Actions/SR/SrRefreshAction.cs, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx
The handling of this alert is a bit unorthodox because it is not listed among the known Message types since it is coming from a xapi plugin and the API is not obliged to know about it.
=> CP-33153: Added friendly title and description for GFS2_CAPACITY alert. Corrected scan action description.

.gitignore
On my setup (Windows 10) this file results from attempting to modify my last commit with `git commit --amend`. Cygwin and Git Bash work fine of course. However I'd prefer to ensure that the file doesn't accidentally make it into commits.
=> ignore 'vim.exe.stackdump'

CFUValidator/CFUValidator.csproj, XenAdmin/Network/XenConnectionUI.cs, XenAdmin/TabPages/ManageUpdatesPage.cs, XenAdmin/XenAdmin.csproj, XenAdminTests/XenAdminTests.csproj, XenCenterLib/XenCenterLib.csproj, XenModel/InvisibleMessages.Designer.cs, XenModel/InvisibleMessages.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/Network/XenConnection.cs, XenModel/XenModel.csproj, XenOvfApi/XenOvfApi.csproj, XenOvfTransport/XenOvfTransport.csproj, XenServerHealthCheck/XenServerHealthCheck.csproj, packages/DOTNET_BUILD_LOCATION
1. Fixed 3rd library references in project files (ported from release/stockholm/UPD-624).
2. CA-343781: Fixed error visibility on updates page (ported from release/stockholm/UPD-624).
3. Removed old exception.
1 and 2 do not need review if https://github.com/xenserver/xenadmin/pull/2727 is done first.
=> CA-343781 + 3rd party library references + redundant exception

XenModel/Actions/AsyncAction.cs, XenModel/Actions/Host/RestartToolstackAction.cs, XenModel/Actions/PVS/PvsProxyCreateAction.cs, XenModel/Actions/PVS/PvsProxyDestroyAction.cs, XenModel/Actions/Pool_Patch/RemovePatchAction.cs, XenModel/Actions/SR/SrProbeAction.cs, XenModel/Actions/VM/VMShutdownAction.cs, XenModel/Actions/VM/VMSuspendAction.cs, XenModel/Network/TaskPoller.cs
- CA-339353: SrProbeAction should run its RBAC checks explicitly instead of inheriting from PureAsyncAction. The fix for CA-337280 moved the parsing of the probe result in the Run body of the action, causing it to fail when the dry-run for the RBAC checks is performed.
- Minor modifications to task polling: Consolidated Action.PollToCompletion overloads, among others, to reduce precision loss.
Logging the environment's stack trace is not very useful in the case of an API failure. Log the task's opaque_ref so it's easier to trace errors in the server side logs.
=> CA-339353: Fixed broken SrProbeAction when the logged in user is not local root

XenAdmin/Controls/DiskSpinner.cs, XenAdmin/Controls/SrPicker.cs, XenAdmin/Controls/SrPickerItem.cs, XenAdmin/Dialogs/CopyVMDialog.cs, XenAdmin/Dialogs/MoveVirtualDiskDialog.cs, XenAdmin/Dialogs/NewDiskDialog.cs, XenAdmin/Dialogs/VMDialogs/MoveVMDialog.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/IntraPoolCopyPage.cs, XenAdmin/Wizards/ImportWizard/StoragePickerPage.cs, XenModel/XenAPI-Extensions/VM.cs
Also, set the required disk size to zero when the disk spinner value is invalid.
=> CA-339384: Take account of thin provisioning when placing a disk on a target SR.

XenModel/Actions/OvfActions/Export.cs, XenModel/Actions/OvfActions/Import.cs
I also increased the decimal figures shown when the disk is transferred because for slow networks it's easy to think that progress is stuck.
=> CA-347487: Fixed error formatting.

XenModel/Actions/AsyncAction.cs, XenModel/Actions/Network/DestroyBondAction.cs, XenModel/Actions/VM/VMDestroyAction.cs
Destroying a VM does not disrupt the connection, hence the use of the BestEffort method is not warranted. After this correction, BestEffort is only used in the DestroyedBondAction, hence I removed it completely and replaced it with simpler exception handling in the latter class's Run method.
=> Bad application of the code reusability principle in VMDestroyAction.

XenAdmin/Commands/AddHostCommand.cs, XenAdmin/Commands/AddHostToPoolCommand.cs, XenAdmin/Commands/ApplyLicenseEditionCommand.cs, XenAdmin/Commands/Command.cs, XenAdmin/Commands/Controls/AssignVMGroupToolStripMenuItem.cs, XenAdmin/Commands/Controls/CommandButton.cs, XenAdmin/Commands/Controls/CommandToolStripButton.cs, XenAdmin/Commands/Controls/CommandToolStripMenuItem.cs, XenAdmin/Commands/DeleteVMCommand.cs, XenAdmin/Commands/DestroySRCommand.cs, XenAdmin/Commands/InstallToolsCommand.cs, XenAdmin/Commands/NewFolderCommand.cs, XenAdmin/Commands/RebootCommand.cs, XenAdmin/Commands/RebootHostCommand.cs, XenAdmin/Commands/RemoveHostFromPoolCommand.cs, XenAdmin/Commands/RepairSRCommand.cs, XenAdmin/Commands/ResumeVMCommand.cs, XenAdmin/Commands/ShutDownCommand.cs, XenAdmin/Commands/ShutDownHostCommand.cs, XenAdmin/Commands/StartVMCommand.cs, XenAdmin/Commands/SuspendVMCommand.cs, XenAdmin/Commands/TrimSRCommand.cs, XenAdmin/Commands/VMLifeCycleCommand.cs, XenAdmin/Plugins/Features/MenuItemFeatureCommand.cs, XenAdmin/Plugins/Features/ParentMenuItemFeatureCommand.cs, XenAdmin/TabPages/SrStoragePage.Designer.cs, XenAdmin/TabPages/SrStoragePage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Please review commits separately and with whitespace disabled.
The actual change making the difference in the calculations is the commit with the tooltip refactoring. As an example, I counted the times the method StartVMCommand.CanExecute(VM vm) is hit before and after this change. Previously, on VM selection and on cache update the method was hit 13 and 7 times respectively, after the change these numbers have gone down to 4 and 2. (Ideally we'd like them both to be 1, however this won't be possible unless we combine the CanExecute() and GetCantExecuteReasons() to one method CanExecute(out reasons), which is a big and scary change best left for later).
=> Some refactoring around Commands to improve calculation efficiency

XenModel/XenAPI-Extensions/VM.cs
All currently supported versions of the product support 255 VBDs,
see https://docs.citrix.com/en-us/xenserver/7-0/downloads/config-limits.pdf
When a VM is imported through XCM it may not have recommendations,
and XenCenter falls back to the default, which is 16.
Then adding another disk shows an error that the maximum number of disks was reached,
which contradicts our support statement of 255 disks.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
=> Update DEFAULT_NUM_VBDS_ALLOWED to 255

XenModel/Actions/AsyncAction.cs, XenModel/Actions/Host/HostBackupRestoreAction.cs, XenModel/Actions/Host/SingleHostStatusAction.cs, XenModel/Actions/VM/ExportVmAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/WLB/WlbReportAction.cs, XenModel/XenAPI-Extensions/SR.cs
- CA-352455: Parse the task result as xml document instead of using a regex.
- Do not use the task description as the AsyncAction description because in most cases it is not localised. Also, do not poll if the RelatedTask is null.
=> CA-352455 + issue with action description while polling task

XenAdmin/Dialogs/RoleElevationDialog.cs, XenAdmin/MainWindow.Designer.cs, XenAdmin/MainWindow.cs, XenAdmin/SettingsPanels/VDISizeLocationPage.cs, XenAdmin/Wizards/NewVMWizard/Page_Storage.cs, XenModel/Actions/Action.cs, XenModel/Actions/PureAsyncAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/XenObject.cs
Apart from offering a quick status, this proved useful when I was working on REQ-797, where I had several long actions running and it was very practical to click once on the label and be taken to the Events tab to see what was still in progress (the label would have been hidden otherwise since I didn't have any failed events, and going to the Events tab would have required two clicks via the navigation bar buttons).
The changes in the Action.cs and RoleElevationDialog.cs are things I noticed while debugging.
=> Suggested enhancement: Added Events in progress to the outlook-style status labels of the main window.

XenAdmin/Controls/PoolHostPicker.cs, XenAdmin/Controls/SrPicker.cs, XenAdmin/Controls/SrPickerItem.cs, XenAdmin/Dialogs/CopyVMDialog.cs, XenAdmin/Dialogs/MoveVirtualDiskDialog.cs, XenAdmin/Dialogs/VMDialogs/MoveVMDialog.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/IntraPoolCopyPage.cs, XenAdmin/Wizards/NewVMWizard/Page_Storage.cs, XenModel/Utils/Helpers.cs, XenModel/XenAPI-Extensions/SR.cs
Moving and copying a VM should be treated differently, hence we need a different SrPickerItem subclass for each operation. Minor logic simplifications: I removed the methods ShowInVDISRList and CanCreateVmOn because in an occasion or two they were causing duplication of checks (this happens with other SR extension methods too, but it's out of scope to touch them at this point).
=> CA-353524: Full copy of VM on the same SR is allowed.

XenAdmin/Core/HelpersGUI.cs
Regression introduced in this branch by https://github.com/xenserver/xenadmin/pull/2791 when I moved around the code to fix the branding of the messages.
=> Ensure there are servers whose CPU will be downlevelled before showing the warning.

XenServerHealthCheck/XenServerHealthCheck.csproj
The dll CookComputing.XmlRpcV2 is copied over anyway because it is a dependency of XenModel.
=> The Healthcheck service does not need any direct references to the XmlRpc dll

XenAdmin/Wizards/ExportWizard/ExportOptionsPage.cs
After having removed the restriction for non-empty passwords, the certificate validation still works.
Tested with the following combinations:
.pem | .pfx | Correct Password | Incorrect Password | Empty Password
-- | -- | -- | -- | --
NO password | NO password | N/A | ✅ As expected | ✅ As expected
WITH password | NO password | N/A | ✅ As expected | ✅ As expected
NO password | WITH password | ✅ As expected | ✅ As expected | ✅ As expected
WITH password (different) | WITH password (different) | ✅ As expected | ✅ As expected | ✅ As expected
WITH password(same) | WITH password    (same) | ✅ As expected | ✅ As expected | ✅ As expected
.pem was generated with:
```openssl req -x509 -newkey rsa:2048 [-nodes] -sha256 -days 29 -keyout key29days.pem -out cert29days.pem```
.pfx was generated with: …
=> CA-350819: Add support for passwordless certificates

XenModel/Messages.Designer.cs, XenModel/Messages.resx
Entire solution only contains visible strings of the word in Messages.resx and FriendlyErrorNames.resx
Latter has been excluded.
=> CP-37734: Replace negative language with bonded or pool member

XenAdmin/TabPages/GeneralTabPage.Designer.cs, XenAdmin/TabPages/GeneralTabPage.cs
Because of this, the scrollbar is partially visible until these pixels are refreshed manually (either by resizing the window, moving to a different page, or by interacting with controls that occupy the same space.
In order to avoid this, the `AutoScroll` property is updated programmatically whenever the `panel2`'s `Paint` event is fired.
=> CA-279581: Prevent panel headers from overlapping scrollbar

XenModel/XenAPI/Host.cs, XenModel/XenAPI/JsonRpcClient.cs, XenModel/XenAPI/Proxy.cs
This is a correction for https://github.com/xenserver/xenadmin/commit/a3b4ad0de68a6d47cf94a02763422c4d5f371e87. For the time being the overloads for this method have to be provided manually due to CA-355432.
=> Corrected Host.evacuate overloads.

XenAdmin/Controls/CustomDataGraph/ArchiveMaintainer.cs, XenAdmin/Controls/CustomDataGraph/DataRange.cs, XenAdmin/Controls/CustomDataGraph/DataSet.cs, XenAdmin/Controls/CustomDataGraph/GraphHelpers.cs, XenAdmin/Controls/CustomDataGraph/GraphList.cs, XenAdmin/Dialogs/ActionProgressDialog.Designer.cs, XenAdmin/Dialogs/ActionProgressDialog.cs, XenAdmin/Dialogs/ActionProgressDialog.resx, XenAdmin/Dialogs/GraphDetailsDialog.Designer.cs, XenAdmin/Dialogs/GraphDetailsDialog.cs, XenAdmin/Dialogs/GraphDetailsDialog.resx, XenAdmin/Dialogs/RoleElevationDialog.cs, XenAdmin/TabPages/PerformancePage.cs, XenAdmin/XenAdmin.csproj, XenModel/Actions/GetDataSourcesAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- CA-359068: Match the whole datasource name (previously the wrong one was picked for disk read/write latency).
- New/edit Graph dialog: differentiate between enabled/disabled datasources and visible/hidden (known/unknown units; the latter may mean no data).
- Some refactoring.
=> Corrected calculation of datasource units (CA-359068). New/Edit Graph dialog enhancements.

XenAdmin/Alerts/Types/ClientUpdateAlert.cs, XenAdmin/TabPages/ManageUpdatesPage.cs
Added the interface option to download and install updates for client updates. Disabled by default until CP-31587 does the proper checks
Signed-off-by: Christophe25 <christopher.lancaste1@citrix.com>
=> CP-32667 Added download action to CHC

XenAdmin/Commands/DisconnectCommand.cs, XenAdmin/TabPages/AdPage.cs, XenAdmin/TabPages/AdPage.resx, XenModel/Actions/AD/AddRemoveRolesAction.cs, XenModel/Actions/AD/AddRemoveSubjectsAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/Utils/Helpers.cs
Best reviewed commit-by-commit. Whitespace differences are the automatic indent as completed by VS2019.
Took advantage to improve UX slightly:
- Grouped logging out actions into a `MultipleAction` to avoid one RBAc prompt per user disconnection
- Tell user that they're also going to disconnect other users when the selected users include the current one.
Users will still need to insert credentials for two RBAC prompts if they're changing roles to logged in users (one for changing the roles, one for disconnections if necessary). Not ideal but it makes the code tidier since we can reuse methods.
Tested with:
| Changing current user 	| Changing other user(s) 	| Other user(s) are(is) logged in 	| More than one user involved 	| Result 	|
|:---:	|:---:	|---	|---	|---	|
| NO 	| YES 	| NO 	| YES …
=> CA-343229: Changing roles when logged in as an AD user only takes effect after logging out/in

XenModel/Messages.Designer.cs, XenModel/Messages.resx
Also removes the wording related to permanent dismissal, since we give users the option to restore update notifications.
Please advise on if the new wording does not correctly reflect XC's behaviour here.
=> (Stockholm) CA-362018: Improve update notification dismissal message

XenModel/Actions/OvfActions/Export.cs, XenModel/Actions/OvfActions/Import.cs, XenOvfApi/OVF.cs
Didn't change other calls to `OVF.SetCPUs`, since the code is quite complex. If anyone can advise on which ones can be updated, I'll make those changes as well.
Change makes use of the `rasd:Limit` element of the `Item` tag representing vCPUs.
It is described by the [specification (see 7.7.11)](http://www.dmtf.org/standards/published_documents/DSP1041_1.1.pdf) as
>  `rasd:Limit`: A client may set the value of the Limit property to specify the maximum amount of host resource that is requested by the virtual resource allocation request.
=> CA-361078: vCPUs count isn't exported/imported within OVFs

XenAdmin/Wizards/ConversionWizard/ConversionNetworkPage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateNetworkingPage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrationNetworkResource.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs, XenAdmin/Wizards/GenericPages/NetworkResource.cs, XenAdmin/Wizards/GenericPages/SelectMultipleVMNetworkPage.cs, XenAdmin/Wizards/ImportWizard/OvfNetworkResource.cs, XenModel/Actions/VM/VMCrossPoolMigrateAction.cs, XenModel/Mappings/VmMapping.cs, XenModel/XenAPI-Extensions/Failure.cs
Probably best reviewed at once. Also contains minor style fixes.
Since the two issues addressed here are quite tangled, this PR attempts to fix both:
- Fixes VIF mapping in cross pool migration by reflecting the parameters of the corresponding xapi method
- Adds snapshot VIFs to mapping if they are not present within the ones returned by `VM.VIFs` (e.g.: VIF was deleted before cross pool migration, but after snapshot creation)
=> CA-359124 & CA-360426: Add snapshot VIFs to mapping during cross pool migration & fix VIF mapping in cross pool migration

.github/workflows/main.yml, scripts/check_strings_sorting.ps1, scripts/sort_strings.ps1
As shown by the commits, this PR adds two new scripts and one step to the PR/push action.
It uses the `Sort` function in PowerShell to compare strings.
The action step doesn't reorder. While it was suggested to add it to the pre-push hook, I don't think it'd be a good idea to add side effects like this to hooks. Feel free to comment on the matter.
=> CA-361926: Ensure `Messages.resx` in XenCenter stays alphabetically sorted

XenAdmin/ConsoleView/VNCTabView.cs, XenAdmin/ConsoleView/VNCTabView.resx, XenAdmin/Dialogs/OptionsDialog.Designer.cs, XenAdmin/Dialogs/OptionsDialog.cs, XenAdmin/Dialogs/OptionsDialog.resx, XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.Designer.cs, XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.cs, XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.ja.resx, XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.resx, XenAdmin/Dialogs/OptionsPages/ExternalToolsOptionsPage.zh-CN.resx, XenAdmin/MainWindow.Designer.cs, XenAdmin/MainWindow.cs, XenAdmin/Program.cs, XenAdmin/Properties/Settings.Designer.cs, XenAdmin/Properties/Settings.settings, XenAdmin/Settings.cs, XenAdmin/TabPages/GeneralTabPage.Designer.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/TabPages/GeneralTabPage.resx, XenAdmin/XenAdmin.csproj, XenAdmin/app.config, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/SshConsole.cs, XenModel/XenModel.csproj
Some automatic whitespace changes so I suggest you remove those diffs.
Tried to make it easy to review commit-by-commit.
You won't be able to see the "warning" version of the error dialog unless CHC can't find either client on first start-up. So best approach is probably to temporarily rename the `.exe`s.
Defaults paths are:
`C:\Windows\System32\OpenSSH\ssh.exe`
`C:\Program Files\PuTTY\putty.exe`
=> CP-38529: Replace built-in PuTTY with user-provided location

XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx, XenModel/XenAPI/FriendlyErrorNames.resx, XenModel/XenAPI/JsonRpcClient.cs, XenModel/XenAPI/Message2.cs, XenModel/XenAPI/Pool.cs, XenModel/XenAPI/Proxy.cs, XenModel/XenAPI/Task.cs, XenModel/XenModel.csproj
This PR contains a temporary fix to the SDK. ~Commit can be removed if we instead prefer to update the entire SDK.~ 
🚨🚨🚨🚨🚨
SDK has been updated to `xapi 21.3.0/1.xs8`, **with a modification** needed to avoid issues related to CA-355432 as pointed out by @kc284.
🚨🚨🚨🚨🚨
The following additions have been made:
```
vm_migrated
vm_snapshotted
vm_snapshot_reverted
vm_checkpointed
vm_paused
vm_unpaused
```
=> CP-38814: Add friendly names to new xapi alerts

XenAdmin/Commands/HACommand.cs, XenAdmin/Commands/InstallToolsCommand.cs, XenAdmin/Controls/Wlb/WlbOptimizePool.cs, XenAdmin/Core/HealthCheck.cs, XenAdmin/Dialogs/RoleSelectionDialog.cs, XenAdmin/TabPages/WlbPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs, XenModel/Actions/AD/AddRemoveRolesAction.cs, XenModel/PoolJoinRules.cs, XenModel/RbacMethod.cs, XenModel/XenAPI-Extensions/Role.cs, XenModel/XenAPI-Extensions/Session.cs
Commits best viewed separately.
=> CP-38893: Make internal roles unavailable for selection. Some refactoring of Role extension method overloads.

XenModel/Actions/OvfActions/Import.cs
VMWare OVFs don't export the value, which caused an exception to be thrown when importing them.
If you need a VMWare OVF to test this, feel free to DM me.
=> CA-361078: Parse OVFs without a `Limit` element in the vCPUs section

XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateCanMigrateFilter.cs, XenModel/XenAPI-Extensions/Failure.cs, XenModel/XenAPI/FriendlyErrorNames.Designer.cs, XenModel/XenAPI/FriendlyErrorNames.resx
Note that the change in FriendlyErroNames should be part of an SDK drop really, but for the time being I have added it as an isolated change  until the server side changes are merged and the issues plaguing the SDK generation are solved.
=> CA-365297, CP-39323: DMC checks when attempting cross-pool migration

XenAdmin/Controls/CustomDataGraph/LineRenderer.cs
Sharp turns in the graph can result in the line being drawn outside of the box.
This change makes sure the line is only rendered within the input rectangle.
It's easier to replicate if you shrink the window size as much as possible
=> CA-334613: Clip region within which performance graph lines are drawn

XenAdmin/Diagnostics/Checks/DR/AssertCanBeRecoveredCheck.cs, XenAdmin/Diagnostics/Problems/PoolProblem/MissingSRProblem.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.Designer.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardPrecheckPage.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
- Re-arranged and re-worded controls so that this page looks more like
the precheck page of the patching and RPU wizards.
- Do not show the failure message unless issues are found.
- Do no enable the Resolve All button unless all issues are fixable.
- Fixed crash when the required SR is present in the pool but detached.
=> Some corrections on the DRWizard prechecks page:

.github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Let's see if it works and then I'll make the change in our other repos too.
=> Added code owners (default reviewers).

XenAdmin/Commands/DragDropCrossPoolMoveHaltedVMCommand.cs, XenAdmin/Commands/DragDropMigrateVMCommand.cs, XenAdmin/Controls/MainWindowControls/NavigationView.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Also, show the name of the VM in the various failure messages as drag-and-drop may operate on multiple VMs.
=> CA-329538: Tell the user to ensure tools are installed if a VM cannot be migrated via drag-and-drop

XenAdmin/Wizards/DRWizards/DRFailoverWizard.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardRecoverPage.Designer.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardRecoverPage.cs, XenAdmin/Wizards/DRWizards/DRFailoverWizardRecoverPage.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Normally we don't change the blurb at the top of the page, only the status text at the bottom. I also moved the progress bar to the bottom, so now the only wizard page where the progress bar is not at the bottom is the `AutomatedUpdates` page.
=> Some layout and logic changes so the `DRFailoverWizardRecoverPage` looks and behaves more like the other wizard pages with progress bars

scripts/xenadmin-build.sh
Previously, the URL would point to the XML itself, causing checksum check errors
Also fixes issue whereby building non-branded builds would fail
=> Point URL in `CHCUpdates.xml` to MSI location

XenAdmin/Controls/SmartScrollTextBox.cs, XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs, XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.designer.cs, XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.resx, XenAdmin/Wizards/PatchingWizard/PatchingWizard_UploadPage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeUpgradePage.cs, XenAdmin/XenAdmin.csproj, XenCenterLib/Win32.cs
Only the first one contains the fix.
The others are to tidy some aspects of the code.
Feel free to weigh in on the naming and/or location of `AppTextBox`, I wasn't sure what to choose for them.
_______
The basic idea here is that we're not automatically keeping the `TextBox` scrolled all the way down if the user has moved the scrollbar.
If they move it back to the bottom, it'll go back to scrolling automatically.
I have also made the event return the `newPosition` of the bar, and added _ad-hoc_ logic for the horizontal scrollbar. This is just so this event is ready for other use cases that might arise in the future.
=> CA-293683: Prevent automatic scrolling in RPU wizard if user has scrolled manually

XenAdmin/Actions/GUIActions/SaveDataSourceStateAction.cs, XenAdmin/Controls/CustomDataGraph/ArchiveMaintainer.cs, XenModel/Actions/GetDataSourcesAction.cs
Note that I have only handled the exception when get_data_sources is called in the ArchiveMaintainer. The other two instances of the call are in the Run() method of GetDataSourcesAction and EnableDataSourceAction and exceptions thrown there are handled by the actions' base class.
=> CA-366140: Reverted original solution. Handled error thrown when retrieving datasources.

XenAdmin/Controls/CustomDataGraph/ArchiveMaintainer.cs
Looks like it was a little regression we missed when reviewing 581a9c41ee7b1b4452cfda9ca97b333a35d6611e.
🤷‍♂️
=> CA-368528: Fix performance data not being updated after a few seconds on VMs

XenAdmin/Controls/CustomDataGraph/DataPlot.cs, XenAdmin/Controls/CustomDataGraph/LineRenderer.cs
Resetting the clip so that on the next render we don't hide labels and title.
Also moved logic outside `LineRenderer.cs`
Below is an after / before comparison. The below is the build before the fix for CA-334613 was merged.
=> CA-368958: Reset clip region once performance lines are drawn

XenAdminTests/XenAdminTests.csproj, XenModel/XenModel.csproj, packages/DOTNET_BUILD_LOCATION
For Stockholm LCM some `dotnet-packges` changes are necessary (see CA-369804). Another PR will follow once those have been completed.
The `packages/DOTNET_BUILD_LOCATION` points to release but you should be using the internal location for testing.
=> CA-368321: Update Json.NET from `10.0.2` to `13.0.1`

XenAdmin/Core/Registry.cs
I had fixed that on the LCM branch within PR https://github.com/xenserver/xenadmin/pull/2891 but never ported to master. The advantage of this change is that one can leave the override keys in the registry with empty values.
=> Guard against registry keys returning empty strings.

Jenkinsfile, XenAdmin/Core/Registry.cs
Now that we have made the updates URL a branded string both on `master` and `release/stockholm/lcm` (see https://github.com/xenserver/xenadmin/pull/3037 and https://github.com/xenserver/xenadmin/pull/2976), the default value in the code is a placeholder and results in an error, so in order to debug the application one always needs to fill  `Computer\HKEY_CURRENT_USER\SOFTWARE\[Citrix]\[XenCenter]\CheckForUpdatesXmlLocationOverride` in the registry with a proper location (URL or file). So far the aforementioned location served both branches, but the values are not the same for both. This PR makes the application read from `Computer\HKEY_CURRENT_USER\SOFTWARE\[Citrix]\[XenCenter_No_Space]\CheckForUpdatesXmlLocationOverride)` when running from source code on master. Note that the change …
=> Corrected registry key name; bumped branding.

scripts/re-branding.sh
Without the change, `[UPDATES_URL]` string in `Branding/Branding.resx` isn't changed.
=> Apply rebranding to `Branding/Branding.resx`

XenAdmin/Wizards/BugToolWizardFiles/BugToolPageSelectCapabilities.cs
Linq.Intersect was failing to combine server capabilities because the helper class did not implement GetHashCode.
=> CA-370847: Unable to collect status report for multiple servers

XenAdmin/Commands/AddVirtualDiskCommand.cs, XenAdmin/Controls/AffinityPicker.Designer.cs, XenAdmin/Controls/AffinityPicker.cs, XenAdmin/Dialogs/NewDiskDialog.cs, XenAdmin/TabPages/SrStoragePage.cs, XenAdmin/Wizards/NewVMWizard/NewVMWizard.cs, XenAdmin/Wizards/NewVMWizard/Page_HomeServer.Designer.cs, XenAdmin/Wizards/NewVMWizard/Page_HomeServer.cs
- The Finish page of the NewVM wizard was not showing the selected home server correctly.
- Disable the Rescan button on the SR storage page when the SR is detached because the operation fails anyway.
- Removed NewDiskDialog constructor as it was not particularly useful.
=> Random fixes:

XenAdmin/Commands/StartVMCommand.cs, XenAdmin/Controls/SrPicker.cs, XenAdmin/Controls/SrPickerItem.cs, XenAdmin/Dialogs/NewDiskDialog.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/Wizards/NewVMWizard/Page_Storage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizard.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/XenAPI-Extensions/SR.cs
`VdiCreationCanProceed` is only used for this use case and when a new VM is being created. In the latter case, we don't really care about physical utilisation of VMs, since it's only checking template disk sizes.
=> CA-359965: Consider `physical_utilisation` value when checking for free space in thinly provisioned SRs

XenAdmin/Wizards/PatchingWizard/PlanActions/RebootPlanAction.cs, XenModel/Network/IXenConnection.cs, XenModel/Network/XenConnection.cs
This is only one type of solution. We could also:
- use `Connection.ExpectDisruption` insted of the new field.
- Never set `_promptForNewPassword` to null after disconnection. I didn't because there might be a reason and I didn't want to set side effects. However not doing so might mean that the issue could prop up under a different plan action. (I didn't find it, but I'm not knowledgeable around this domain)
Once it's merged, we can backport to Stockholm, too
=> CA-371356 [XSI-1327]: Add option to prevent resetting pwd prompt function on disconnection

XenAdmin/Controls/SrPicker.cs, XenAdmin/Controls/SrPickerItem.cs, XenAdmin/Core/HelpersGUI.cs, XenAdmin/Dialogs/CopyVMDialog.Designer.cs, XenAdmin/Dialogs/CopyVMDialog.cs, XenAdmin/Dialogs/CopyVMDialog.resx, XenAdmin/Dialogs/MoveVirtualDiskDialog.Designer.cs, XenAdmin/Dialogs/MoveVirtualDiskDialog.cs, XenAdmin/Dialogs/MoveVirtualDiskDialog.resx, XenAdmin/Dialogs/NewDiskDialog.Designer.cs, XenAdmin/Dialogs/NewDiskDialog.cs, XenAdmin/Dialogs/NewDiskDialog.resx, XenAdmin/Dialogs/VMDialogs/MoveVMDialog.Designer.cs, XenAdmin/Dialogs/VMDialogs/MoveVMDialog.cs, XenAdmin/Dialogs/VMDialogs/MoveVMDialog.resx, XenAdmin/TabPages/SrStoragePage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/IntraPoolCopyPage.Designer.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/IntraPoolCopyPage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/IntraPoolCopyPage.resx, XenAdmin/Wizards/ImportWizard/StoragePickerPage.Designer.cs, XenAdmin/Wizards/ImportWizard/StoragePickerPage.cs, XenAdmin/Wizards/ImportWizard/StoragePickerPage.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx
The scans run in parallel in batches of three to avoid flooding the session. Also, prevent firing the SelectedIndexChanged event multiple times when populating the NewDisk dialog. Renamed the SrPicker control on the latter (because SrListBox is a different type of control).
=> CP-41048: Add each SR to the SrPicker as soon as its scan finishes, without waiting for the other scans to finish.

XenAdmin/Core/ExtensionMethods.cs
`value` can sometimes be fed as a multiline string, in which case timestamps were added to empty lines, causing confusion.
Will port to master once this is approved.
=> Do not prepend empty lines with a timestamp in `AutomatedUpdatesBasePage`

XenAdmin/Core/ExtensionMethods.cs
`value` can sometimes be fed as a multiline string, in which case timestamps were added to empty lines, causing confusion.
Signed-off-by: Danilo Del Busso <danilo.delbusso@cloud.com>
=> [master] Do not prepend empty lines with a timestamp in `AutomatedUpdatesBasePage`

XenAdmin/Controls/CustomDataGraph/DataSet.cs, XenAdmin/Controls/CustomDataGraph/GraphHelpers.cs, XenAdmin/Dialogs/GraphDetailsDialog.Designer.cs, XenAdmin/Dialogs/GraphDetailsDialog.cs, XenAdmin/Dialogs/GraphDetailsDialog.resx, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.ja.resx, XenModel/FriendlyNames.resx, XenModel/FriendlyNames.zh-CN.resx
- Expose some hidden data sources to UI 
- Update friendly name for xapi_open_fds data source
- Also apply string sorting
- Add data source description as column in GraphDetailsDialog
- Increase default GraphDetailsDialog width to accomodate new column
Also:
Tidy up source in GraphDetailsDialog
- Rename fields
- Reorder methods
- Rename methods
- Add `sealed` to `DataSourceGridViewRow`
_________________
This PR also fixes #3080
=> CP-40157: Updates to `GraphDetailsDialog`

XenModel/Actions/ZipStatusReportAction.cs
Regression introduced on line [103](https://github.com/xenserver/xenadmin/blob/master/XenModel/Actions/ZipStatusReportAction.cs#L103) as part of #3087. Built application was trying to insert file in the installation directory, for which it had no permission.
=> CA-375282: Insert sanitised TARs into Temp folder

WixInstaller/XenCenter.wxs
FYI: While reviewing, you can use the example used in the ticket to check if the MSI has the correct permissions, since this branch doesn't contain 39b84bbcc5bfa282e0baf2deb73e07b2f076936e.
_________________
The XenCenter executable was started with elevated privileges even with use of `Impersonate = "yes"`, and `WixShellExecTarget` was actually ignored.
What helped debug the issue was the [wix 3 docs](https://wixtoolset.org/docs/v3/howtos/ui_and_localization/run_program_after_install/#step-3-include-the-custom-action), which point to the use of the `WixCA:WixShellExec` function, with the executable being its target.
> "Why did XenCenter.exe run under elevated privileges even if `Impersonate` was set to `"yes"`"
I do not know. The [`CustomAction` …
=> CA-375346: Point to Wix Shell instead of executable when launching XenCenter

XenAdmin/Controls/SrPicker.cs, XenAdmin/Dialogs/NewDiskDialog.cs, XenAdmin/Wizards/NewVMWizard/Page_Storage.cs
Also fixed issue where the SR was not preselected when editing an existing disk and no scans were taking place.
=> (LCM) CA-375173: Create the VDI and VBD records before closing the new disk dialog

XenAdmin/Wizards/NewVMWizard/Page_Template.cs, XenModel/XenAPI-Extensions/VM.cs
- Moved Windows Server templates to a different category.
- Show templates in reverse alphabetical (typically release) order.
=> Reordered templates on the NewVM wizard:

XenAdmin/Diagnostics/Checks/PoolHasDeprecatedSrsCheck.cs, XenAdmin/Diagnostics/Problems/PoolProblem/PoolHasFCoESrWarning.cs, XenAdmin/Diagnostics/Problems/Problem.cs, XenAdmin/Diagnostics/Problems/Warning.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/Wizards/NewSRWizard_Pages/ChooseSrTypePage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs, XenAdmin/XenAdmin.csproj, XenModel/InvisibleMessages.Designer.cs, XenModel/InvisibleMessages.resx, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/Utils/Helpers.Versions.cs
There's some tidy-up code here, I suggest you review one commit at a time.
Warnings added to
- RPU wizard from pre-82x
- New SR wizard
- General tab of SR
Note that the XC warning for pre-cloud connections is superseded by this new one. This is by design as there are planned changes to that warning. This is temporary as we will be making changes to that piece of logic, but should enable testing of the feature.
I am redirecting to a vanity link, this will be updated by the docs team once the deprecation has its own page.
=> CP-41737: Add FCoE deprecation warnings

XenAdmin/Wizards/ImportWizard/ImportSourcePage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
The original code was crashing because we switched to .NET framework's compression classes and GZipStream is a bit basic and does not support Position.
I tried to find an alternative method of reporting progress, however, I could not see a reliable way of knowing the uncompressed file size, particularly for the huge gzips handled by the application. The compression ratio depends on the data being compressed and the method and library that was used, which are generally unknown. One solution I thought of was to try to approximate the progress by assuming a compression ratio between 2:1 and 5:1 (typically offered by zlib), but in the end I thought best to just display bytes uncompressed without showing percentage. Let me know what you think.
=> CA-375668: Report bytes uncompressed instead of percentage when uncompressing a gzip.

WixInstaller/XenCenter.wxs, scripts/xenadmin-build.sh
Tested with a Chinese (Simplified) W10 install and a Japanese one.
=> CA-375703: Remove leftover language mentions in `XenCenter.wxs`

XenModel/Actions/OvfActions/Import.cs
Looks like we had been passing compressed streams for a while. However, they were working before passing the `format` parameter to the `import_raw_vdi` call. My guess is that [`vhd-tool`](https://github.com/xapi-project/vhd-tool) is decompressing it, but I haven't gotten that far yet.
Either way, this solution seems to work for all VHDs (compressed or otherwise), and doesn't regress the fix that was introduced to ignore zero bytes when importing disks.
=> [master] CA-375556: Pass non-compressed file stream to `HTTP.CopyStream`

XenAdmin/Controls/CustomDataGraph/DataSet.cs, XenModel/FriendlyNames.Designer.cs, XenModel/FriendlyNames.resx
The description has also been updated with this new definition:
https://github.com/xapi-project/xen-api/pull/4942
=> CP-42286: Add friendly name for `pool_total_session_count`

Jenkinsfile, WixInstaller/XenCenter.wxs, scripts/xenadmin-build.sh
=> Bumped branding to v4.15. Removed leftover references of branded components.

XenAdmin/Commands/Controls/ContextMenuBuilder.cs, XenModel/Utils/Util.cs
Reflection is used quite a lot in the application, but it is a sloppy practice which should be avoided unless absolutely necessary. It generates code smells in static analysers because some of the code appears unused. Most importantly though, it is error prone, which is not obvious before runtime because the compiler cannot catch the issues. In this particular case the MultipleDockerContainers was erroneoulsy marked as abstract, hence a specialised context menu was not constructed for it (we did not notice because the containers feature has been deprecated, but the risk remained).
=> Stop using reflection for the creation of context menu builders; and some smaller corrections.

XenAdmin/Controls/Ballooning/ShinyBar.cs
Resulted in XenCenter hanging with a significant memory leak.
I know what you're going to ask: "How could this possibly happen, anyway?"
Well it happened to me, so here's a PR to fix it 🤷 
To repro the issue "just" edit an OVF to have 10 exabytes of memory, import it, then open its Memory tab (or the host's)
=> Prevent `long` overflow when VM has a very large amount of memory

XenAdmin/Dialogs/AttachDiskDialog.cs, XenAdmin/Dialogs/NewDiskDialog.cs, XenModel/Actions/VBD/VbdCreateAndPlugAction.cs, XenModel/Actions/VM/CreateCdDriveAction.cs, XenModel/XenModel.csproj
- Adding a disk on local SR to an HA protected VM was crashing.
- The user could not plug the disk to the VM even after providing credentials on the role elevation dialog.
- The user had to enter credentials for each of the sub-actions involved in adding a disk.
=> CA-375805: Fixed various issues when an unprivileged user tries to add a disk to a VM:

XenAdmin/Diagnostics/Checks/Check.cs, XenAdmin/Diagnostics/Checks/ClientVersionCheck.cs, XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs, XenAdmin/Diagnostics/Hotfixing/HotfixFactory.cs, XenAdmin/Diagnostics/Problems/Problem.cs, XenAdmin/Diagnostics/Problems/UtilityProblem/EUANotAcceptedProblem.cs, XenAdmin/Diagnostics/Problems/UtilityProblem/EuaNotFoundProblem.cs, XenAdmin/Dialogs/AcceptEuaDialog.Designer.cs, XenAdmin/Dialogs/AcceptEuaDialog.cs, XenAdmin/Dialogs/AcceptEuaDialog.ja.resx, XenAdmin/Dialogs/AcceptEuaDialog.resx, XenAdmin/Dialogs/AcceptEuaDialog.zh-CN.resx, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs, XenAdmin/XenAdmin.csproj, XenModel/Messages.Designer.cs, XenModel/Messages.resx, XenModel/Utils/Helpers.cs, scripts/hotfix-map.json
We only expect Post82X hosts to have this capability. We will be adding a blocking precheck to ensure that all hosts can fetch the EUA. For testing, just ensure you're using the latest XenServer version. Feel free to ping me for help on how to test this locally. Please read the text below to get an understanding of why there are so many changes to `Check`s.
__________________________________
As part of this PR, I had to introduce the concept of a "permanent" check.
> Why can't we just add a normal check?
`Check` instances are created when the prechecks page is created or when the user hits on _Check again_ or _Resolve all_. This is usually fine because the `Check` objects look for changes in the properties or configuration of its associated `IXenObject`s to see if the `Problem` related to …
=> CP-41573 & CP-41923: Add EUA check to RPU Wizard and bump `RPU005` to 5.0

XenAdmin/Wizards/PatchingWizard/AutomatedUpdatesBasePage.cs
Applies to newly added EUA presence problem
=> CP-41573: Do not attempt problem reversion if `SolutionAction.Connection` is null

XenAdmin/Diagnostics/Checks/HostMemoryPostUpgradeCheck.cs, XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs
- b834a7e842b3042caa716c92c33b491027bc7769 ensures we do not run EUA check for upgrades for pre-82X
- 0dfcc3852abdba193ce0bb5dcf304b2931eb5f6c adds a missing hotfix presence check for `HostMemoryPostUpgradeCheck`
=> CA-379402: Fix EUA check & add hotfix check to `HostMemoryPostUpgradeCheck`

WixInstaller/XenCenter.wxs, WixInstaller/wix_src.patch
When an instance of XenCenter is already running, the installer shows the `MsiRMFilesInUse` fragment. Pressing OK within that fragment with the `WixUIRMOption` property set to `UseRM` means that the `RMShutdownAndRestart` event kicks in at the end of the installation.
This happens at the same time as the existing "Launch XenCenter" event (if the matching checkbox is checked), causing in the executable being started twice at about the same time. My guess is that the pipe system is not initialised at that point, and that's how we get two applications.
To avoid this, this commit adds a new custom property: `XS_WixUIRMPressedOk`. This is set to `1` when the user clicks OK on the `WixUIRMOption`. It allows us to know whether or not that dialog was shown at all, as checking `WixUIRMOption` is …
=> CA-376480, CA-374325, & CA-378489: Prevent two instances from starting after running installer; Add desktop shortcut option; Remove existing shortcuts

XenAdmin/Wizards/GenericPages/SelectMultipleVMDestinationPage.cs, XenAdmin/Wizards/ImportWizard/ImportSelectHostPage.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Found these while writing test scenarios for the changes.
- The `_ovfVCpusCount` was being cleared at every iteration and only one CPU count remained at the end of it. Caused the > 32 vCPUs to not appear on multi-VM imports with mixed vCPU counts
- Ensure the warning is correctly calculated when moving back and fourth within pages
- Ensure warning takes into account every host selected in the selection page. Previously it was only taking into account the `SelectedTarget`, which is the last item that was selected. As part of this, I also added a new message and modified an existing one.
=> Miscellaneous fixes to vCPUs warnings

XenAdmin/Dialogs/AssignLicenseDialog.cs, XenAdmin/MainWindow.cs, XenModel/Utils/Helpers.Versions.cs
This PR is mostly for reasons of consistency as the connection will fail before we get to the place where we check versions (the version check comes after a successful connection).
So now there is an amount of code that can be cleaned up (everything applying to servers earlier than Naples), but it is not of high priority to do it now, it can be done at a later time.
=> Disallow connection to havana servers.

XenAdmin/SettingsPanels/PerfmonAlertOptionsPage.cs
`SelectedValue` is always `null` because of the use of `ToStringWrapper`
=> CA-380718: Ensure language code is passed when running `PerfmonOptionsDefinitionAction`

XenAdmin/Diagnostics/Checks/UpgradeRequiresEUA.cs, XenModel/Utils/Helpers.cs
The `Uri` constructor removes `:` after the IP/Host name for NFS storage
=> CA-381017: Pass `OriginalString` when fetching EUA

XenAdmin/ConsoleView/RdpClient.cs, XenAdmin/ConsoleView/VNCTabView.cs, XenAdmin/ConsoleView/XSVNCScreen.cs, XenAdmin/RDP/IRdpClient.cs, XenAdmin/RDP/MsRdpClient9.cs, XenAdmin/XenAdmin.csproj
I split into commits so it's easier to review them, since the PR contains a lot of tidying up for `XSVNCScreen`.
If you want to reproduce the issue this is fixing, just add multiple calls to `ThreadPool.QueueUserWorkItem(TryToConnectRDP);` in `VNCTabView.cs:1178`:
```csharp
if (vncScreen.RdpIp == null)
toggleConsoleButton.Enabled = false;
ThreadPool.QueueUserWorkItem(TryToConnectRDP);
ThreadPool.QueueUserWorkItem(TryToConnectRDP);
ThreadPool.QueueUserWorkItem(TryToConnectRDP);
ThreadPool.QueueUserWorkItem(TryToConnectRDP);
ThreadPool.QueueUserWorkItem(TryToConnectRDP);
```
The changes in 2f8dde440622a70da699906e60f64398bf427cd8 prevent `AccessViolationException`s being called, as they're hit when two instances of `AxMSTSCLib.AxMsRdpClient9` call `Connect` on the same IP + Port …
=> CA-379640, CA-356178, CA-370866: Do not reset remote consoles if they're still attempting connection to a VM

XenAdmin/TabPages/ManageCdnUpdatesPage.cs
1. Exporting from standalone hosts caused the name of the server to be printed twice since the pool has the same name as the host
2. Added the name of the post update action section
=> CA-381678: Fix misc wording issues in `ManageCdnUpdatesPage` export file

XenCenterLib/NamedPipes.cs
Pipes can be created with invalid characters in their names (such as `|`). This results in an exception being thrown when those files are accessed via standard API calls such as `Directory.GetFiles`. Other processes might create these pipes and inadvertently prevent XenCenter from starting altogether.
=> CA-382850: Catch exception when listing pipe names with invalid characters

XenAdminTests/CodeTests/AssemblyTests.cs
#3238 broke the build because ignored tests cause the final result to be "warning" and the pipeline requires "passed".
=> Removed ignored test to fix broken build.

scripts/xenadmin-build.ps1
This ports to master the corrections committed on release/2023/e via PRs #3231, #3232, #3233.
=> (master) Removed erroneously added backslashes. Generate the xml files without the BOM.

XenModel/XenAPI-Extensions/VM.cs
- Min and max should also include the defaults when looking across all templates
- Ensure exception isn't hit unnecessarily when parsing restriction value for VMs
- Allow use of `GetRestrictionValueFromMatchingTemplate` with template objects
- Parallelize `GetRestrictionValueAcrossTemplates` call
=> CA-384191: Fix missing values for min VM restrictions

XenModel/Actions/ParallelAction.cs
One could also fix this by not running actions as soon as the `EnqueueAction` is called (or maybe calling `Monitor.Wait` before the actions have started), but I didn't want to touch a lot of this code and potentially add new issues.
_______
The issue we're fixing here is that there is a chance that all actions have completed before we hit the `Wait` call, we need to make sure we don't hit a deadlock.
This can happen if for instance there is only one action, and it is a "dummy" action, such as the one used in the EUA check.
Also I have removed the compound assignment for the `volatile _completedActionsCount` since Visual Studio was flagging it as a "suspicious usage of a volatile variable". I personally don't think it's a problem but better safe than sorry.
Contains minor whitespace fixes, …
=> CA-379971: Ensure `ParallelAction` is not waiting on `_lock` when no actions are running

XenAdmin/Diagnostics/Checks/AssertCanEvacuateCheck.cs, XenAdmin/Diagnostics/Checks/HaWlbOffCheck.cs, XenAdmin/Diagnostics/Problems/PoolProblem/HAEnabledProblem.cs, XenAdmin/Diagnostics/Problems/PoolProblem/WLBEnabledProblem.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardPrecheckPage.cs, XenModel/Actions/WLB/DisableWLBAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
Plus another couple of issues. Please review each commit separately.
=> CA-383040/XSI-1500: Resume WLB when reverting resolved actions after an update

XenModel/Actions/NRPE/NRPEHostConfiguration.cs, XenModel/Actions/NRPE/NRPEUpdateAction.cs
There is a bug caused by [CA-384572](https://issues.citrite.net/browse/CA-384572). NRPE service can't start after RPU from Yangtze to XS 8 Stream.
The certificate used by NRPE which is generated in Yangtze has no permission. This leads the NRPE operation command (start, restart, etc) failed.
A workaround is that XenCenter sends 'control' command before NRPE enabled. ('control' will modify the permission of certificate)
=> CA-384579: Call previous NRPE plugin xapi to resolve certs permission issue

XenAdmin/Alerts/Types/OutOfSyncWithCdnAlert.cs, XenAdmin/Commands/PoolUpdatesCommand.cs, XenAdmin/Controls/DataGridViewEx/DataGridViewExRow.cs, XenAdmin/Controls/PDSection.cs, XenAdmin/Core/Updates.cs, XenAdmin/Diagnostics/Problems/PoolProblem/CdnOutOfSyncProblem.cs, XenAdmin/Dialogs/ServerUpdates/ConfigCdnUpdatesPage.cs, XenAdmin/TabPages/GeneralTabPage.cs, XenAdmin/TabPages/ManageCdnUpdatesPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_PrecheckPage.cs, XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectServers.cs, XenModel/Actions/Updates/CheckForCdnUpdatesAction.cs, XenModel/Actions/Updates/SyncWithCdnAction.cs
Please review each commit separately.
=> Small corrections to repo syncing and the behaviour of some gridview rows

XenAdmin/Commands/CrossPoolMigrateCommand.cs, XenAdmin/Commands/VMOperationHostCommand.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/CrossPoolMigrateDestinationPage.cs, XenAdmin/Wizards/CrossPoolMigrateWizard/Filters/CrossPoolMigrateFilter.cs, XenAdmin/XenAdmin.csproj
There are 2 commits for easier review, but can be squashed when merging.
=> CA-383483: Rewrote the migration logic to fix regression

XenAdmin/ConsoleView/VNCTabView.Designer.cs, XenAdmin/ConsoleView/VNCTabView.cs, XenAdmin/ConsoleView/VNCTabView.resx, XenAdmin/Controls/ComboBoxes/ISODropDownBox.cs, XenAdmin/Controls/MultipleDvdIsoList.Designer.cs, XenAdmin/Controls/MultipleDvdIsoList.cs, XenAdmin/Controls/MultipleDvdIsoList.resx, XenModel/Actions/VBD/VbdCreateAndPlugAction.cs, XenModel/Messages.Designer.cs, XenModel/Messages.resx
The inconsistency is in commit 81a269522c66c774afdb2b52a6fec5a51ffc6945
Commits best reviwed separately.
=> CP-43651, one inconsistency, layout tweaks, and minor refactoring on MultipleDvdIsoList.

Jenkinsfile, WixInstaller/wix_src.patch
The patch was skipped, and the "Launch XenCenter" button did not show anymore. This was because the custom property `XS_WixUIRMPressedOk` is defined within the patch.
Regressed after dd98fe67 because the way we're applying patches with the PowerShell script doesn't like the `diff --git` format.
I suspect it's got something to do with defining proper directories using `git apply --directory` but an easy solution (this one) is to just use `git -ru`
=> CA-385151 & CP-45516: Fix skipped patch + Bump pipeline to v4.12
